import { CategoryItem, ProductItem, BannerItem, CouponItem, StoreSettings } from './types';

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: 'Jawata Mart',
  tagline: 'Your Trusted Online Shopping Destination in Bangladesh',
  phone: '01915210799',
  email: 'jawatamart@gmail.com',
  address: 'Uttara Sector-12, Dhaka, Bangladesh',
  bkashMerchantNumber: '01915210799',
  nagadMerchantNumber: '01915210799',
  insideDhakaFee: 60,
  outsideDhakaFee: 120,
  freeDeliveryThreshold: 2000,
  sslcommerzStoreId: process.env.SSLCOMMERZ_STORE_ID || 'testbox',
  sslcommerzIsLive: process.env.SSLCOMMERZ_IS_LIVE === 'true',
};

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-baby-kids',
    name: 'Baby & Kids',
    slug: 'baby-kids',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&h=600&fit=crop',
    description: 'Diapers, baby food, clothing, toys, feeding, and strollers',
    icon: 'Baby',
    isFeatured: true,
    order: 1,
    isActive: true,
    subCategories: [
      { id: 'sub-diapers', categoryId: 'cat-baby-kids', name: 'Diapers & Wipes', slug: 'diapers-wipes', order: 1 },
      { id: 'sub-baby-food', categoryId: 'cat-baby-kids', name: 'Baby Food & Formula', slug: 'baby-food', order: 2 },
      { id: 'sub-baby-care', categoryId: 'cat-baby-kids', name: 'Baby Skincare & Bath', slug: 'baby-skincare', order: 3 },
      { id: 'sub-toys', categoryId: 'cat-baby-kids', name: 'Toys & Learning', slug: 'toys-learning', order: 4 },
      { id: 'sub-strollers', categoryId: 'cat-baby-kids', name: 'Strollers & Gear', slug: 'strollers-gear', order: 5 },
    ],
  },
  {
    id: 'cat-mother-maternity',
    name: 'Mother & Maternity',
    slug: 'mother-maternity',
    image: 'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=600&h=600&fit=crop',
    description: 'Maternity wear, breast pumps, pregnancy care, and nursing supplies',
    icon: 'HeartHandshake',
    isFeatured: true,
    order: 2,
    isActive: true,
    subCategories: [
      { id: 'sub-maternity-wear', categoryId: 'cat-mother-maternity', name: 'Maternity Wear', slug: 'maternity-wear', order: 1 },
      { id: 'sub-nursing', categoryId: 'cat-mother-maternity', name: 'Breast Pumps & Nursing', slug: 'nursing-supplies', order: 2 },
      { id: 'sub-pregnancy-care', categoryId: 'cat-mother-maternity', name: 'Pregnancy Care & Vitamins', slug: 'pregnancy-care', order: 3 },
      { id: 'sub-postpartum', categoryId: 'cat-mother-maternity', name: 'Postpartum Essentials', slug: 'postpartum', order: 4 },
    ],
  },
  {
    id: 'cat-mens-fashion',
    name: "Men's Fashion",
    slug: 'mens-fashion',
    image: 'https://images.unsplash.com/photo-1611608776653-f6110bb47067?w=600&h=600&fit=crop',
    description: 'Panjabis, shirts, denim, polos, formal wear, and accessories',
    icon: 'Shirt',
    isFeatured: true,
    order: 3,
    isActive: true,
    subCategories: [
      { id: 'sub-panjabi', categoryId: 'cat-mens-fashion', name: 'Panjabis & Kurtas', slug: 'panjabis', order: 1 },
      { id: 'sub-shirts', categoryId: 'cat-mens-fashion', name: 'Formal & Casual Shirts', slug: 'mens-shirts', order: 2 },
      { id: 'sub-jeans', categoryId: 'cat-mens-fashion', name: 'Jeans & Chinos', slug: 'mens-jeans', order: 3 },
      { id: 'sub-mens-shoes', categoryId: 'cat-mens-fashion', name: 'Footwear & Loafers', slug: 'mens-shoes', order: 4 },
    ],
  },
  {
    id: 'cat-womens-fashion',
    name: "Women's Fashion",
    slug: 'womens-fashion',
    image: 'https://images.unsplash.com/photo-1697020440966-ced476de15bd?w=600&h=600&fit=crop',
    description: 'Sarees, kurtis, salwar kameez, bags, western wear, and jewelry',
    icon: 'Sparkles',
    isFeatured: true,
    order: 4,
    isActive: true,
    subCategories: [
      { id: 'sub-sarees', categoryId: 'cat-womens-fashion', name: 'Silk & Cotton Sarees', slug: 'sarees', order: 1 },
      { id: 'sub-kurtis', categoryId: 'cat-womens-fashion', name: 'Kurtis & 3-Pieces', slug: 'kurtis-three-piece', order: 2 },
      { id: 'sub-bags', categoryId: 'cat-womens-fashion', name: 'Handbags & Clutches', slug: 'handbags', order: 3 },
      { id: 'sub-jewelry', categoryId: 'cat-womens-fashion', name: 'Jewelry & Watches', slug: 'jewelry-watches', order: 4 },
    ],
  },
  {
    id: 'cat-electronics',
    name: 'Electronics & Gadgets',
    slug: 'electronics-gadgets',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
    description: 'Smartwatches, wireless earbuds, chargers, speakers, and power banks',
    icon: 'Headphones',
    isFeatured: true,
    order: 5,
    isActive: true,
    subCategories: [
      { id: 'sub-audio', categoryId: 'cat-electronics', name: 'Earbuds & Headphones', slug: 'earbuds-headphones', order: 1 },
      { id: 'sub-smartwatches', categoryId: 'cat-electronics', name: 'Smartwatches & Bands', slug: 'smartwatches', order: 2 },
      { id: 'sub-chargers', categoryId: 'cat-electronics', name: 'Power Banks & Cables', slug: 'power-banks-cables', order: 3 },
      { id: 'sub-home-appliances', categoryId: 'cat-electronics', name: 'Smart Home Gadgets', slug: 'smart-home', order: 4 },
    ],
  },
  {
    id: 'cat-beauty',
    name: 'Health & Beauty',
    slug: 'health-beauty',
    image: 'https://images.unsplash.com/photo-1552819289-824d37ca69d2?w=600&h=600&fit=crop',
    description: 'Skincare, serums, haircare, makeup, and personal fragrances',
    icon: 'Flower2',
    isFeatured: true,
    order: 6,
    isActive: true,
    subCategories: [
      { id: 'sub-skincare', categoryId: 'cat-beauty', name: 'Face Serums & Creams', slug: 'skincare-serums', order: 1 },
      { id: 'sub-haircare', categoryId: 'cat-beauty', name: 'Hair Shampoos & Oils', slug: 'haircare', order: 2 },
      { id: 'sub-sunscreen', categoryId: 'cat-beauty', name: 'Sunscreens & Lotions', slug: 'sunscreens', order: 3 },
      { id: 'sub-fragrance', categoryId: 'cat-beauty', name: 'Perfumes & Body Mists', slug: 'fragrance', order: 4 },
    ],
  },
  {
    id: 'cat-home-kitchen',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=600&fit=crop',
    description: 'Cookware, induction cooktops, bedsheets, decor, and organizers',
    icon: 'Home',
    isFeatured: false,
    order: 7,
    isActive: true,
    subCategories: [
      { id: 'sub-cookware', categoryId: 'cat-home-kitchen', name: 'Cookware & Cooktops', slug: 'cookware', order: 1 },
      { id: 'sub-bedding', categoryId: 'cat-home-kitchen', name: 'Bedsheets & Pillows', slug: 'bedding-pillows', order: 2 },
      { id: 'sub-kitchen-tools', categoryId: 'cat-home-kitchen', name: 'Kitchen Storage & Tools', slug: 'kitchen-tools', order: 3 },
    ],
  },
  {
    id: 'cat-food-grocery',
    name: 'Food & Grocery',
    slug: 'food-grocery',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=600&fit=crop',
    description: 'Basmati rice, pure honey, nuts, organic oils, and tea',
    icon: 'Apple',
    isFeatured: false,
    order: 8,
    isActive: true,
    subCategories: [
      { id: 'sub-organic', categoryId: 'cat-food-grocery', name: 'Organic Honey & Ghee', slug: 'organic-honey-ghee', order: 1 },
      { id: 'sub-staples', categoryId: 'cat-food-grocery', name: 'Rice, Spices & Staples', slug: 'rice-spices-staples', order: 2 },
      { id: 'sub-beverages', categoryId: 'cat-food-grocery', name: 'Tea & Coffee', slug: 'tea-coffee', order: 3 },
    ],
  },
  {
    id: 'cat-books',
    name: 'Books & Education',
    slug: 'books-education',
    image: 'https://images.unsplash.com/photo-1620783770629-122b7f187703?w=600&h=600&fit=crop',
    description: 'Bangla literature, Islamic books, academic, and stationery',
    icon: 'BookOpen',
    isFeatured: false,
    order: 9,
    isActive: true,
    subCategories: [
      { id: 'sub-bangla-lit', categoryId: 'cat-books', name: 'Bangla Novels & Literature', slug: 'bangla-literature', order: 1 },
      { id: 'sub-self-help', categoryId: 'cat-books', name: 'Self Help & Islamic Books', slug: 'self-help-islamic', order: 2 },
    ],
  },
  {
    id: 'cat-sports',
    name: 'Sports & Outdoor',
    slug: 'sports-outdoor',
    image: 'https://images.unsplash.com/photo-1663245482988-22fad02654e3?w=600&h=600&fit=crop',
    description: 'Running shoes, fitness gear, gym mats, and volleyballs',
    icon: 'Trophy',
    isFeatured: false,
    order: 10,
    isActive: true,
    subCategories: [
      { id: 'sub-running-shoes', categoryId: 'cat-sports', name: 'Running & Gym Shoes', slug: 'running-shoes', order: 1 },
      { id: 'sub-sports-gear', categoryId: 'cat-sports', name: 'Cricket & Football Gear', slug: 'sports-gear', order: 2 },
    ],
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // 1. Baby & Kids
  {
    id: 'p-pampers-pants',
    name: 'Pampers Premium Protection Diapers Pants (L, 54 Pcs)',
    slug: 'pampers-premium-pants-large',
    categoryId: 'cat-baby-kids',
    categoryName: 'Baby & Kids',
    categorySlug: 'baby-kids',
    subCategoryId: 'sub-diapers',
    subCategoryName: 'Diapers & Wipes',
    brand: 'Pampers',
    price: 1850,
    originalPrice: 2200,
    discount: 16,
    stock: 45,
    sku: 'PAM-L-54',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&h=600&fit=crop',
    ],
    description: 'Ultra-absorbent breathable baby diaper pants designed with soft cottony materials. Up to 12 hours of leakage protection suitable for active toddlers.',
    specifications: {
      'Size': 'Large (9-14 kg)',
      'Count': '54 Pants',
      'Country of Origin': 'Japan / Poland',
      'Type': 'Pants Style',
    },
    badge: 'Bestseller',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 428,
  },
  {
    id: 'p-aveeno-baby-wash',
    name: 'Aveeno Baby Daily Moisture Wash & Shampoo 354ml',
    slug: 'aveeno-baby-daily-moisture-wash',
    categoryId: 'cat-baby-kids',
    categoryName: 'Baby & Kids',
    categorySlug: 'baby-kids',
    subCategoryId: 'sub-baby-care',
    subCategoryName: 'Baby Skincare & Bath',
    brand: 'Aveeno',
    price: 1250,
    originalPrice: 1550,
    discount: 19,
    stock: 60,
    sku: 'AVE-BW-354',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop'],
    description: 'Tear-free hypoallergenic baby wash made with natural oat extract. Gently cleanses without drying delicate newborn skin.',
    specifications: {
      'Volume': '354 ml',
      'Key Ingredient': 'Natural Oat Extract',
      'Formulation': 'Tear-Free, Soap-Free',
    },
    badge: 'Top Rated',
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: 'p-drbrowns-bottles',
    name: "Dr. Brown's Anti-Colic Options+ Narrow Baby Bottle (8oz / 250ml, Pack of 2)",
    slug: 'dr-browns-anti-colic-narrow-bottle-2pk',
    categoryId: 'cat-baby-kids',
    categoryName: 'Baby & Kids',
    categorySlug: 'baby-kids',
    subCategoryId: 'sub-baby-care',
    subCategoryName: 'Baby Skincare & Bath',
    brand: "Dr. Brown's",
    price: 1450,
    originalPrice: 1800,
    discount: 19,
    stock: 35,
    sku: 'DRB-NB-2PK',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&h=600&fit=crop'],
    description: 'Clinically proven internal vent system prevents air swallowing to reduce colic, burping, and gas in infants. BPA-free.',
    specifications: {
      'Capacity': '250ml / 8oz',
      'Pack Size': '2 Bottles',
      'Material': 'BPA-Free Polypropylene',
    },
    badge: 'Doctor Recommended',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 189,
  },

  // 2. Mother & Maternity
  {
    id: 'p-medela-breast-pump',
    name: 'Medela Harmony Manual 2-Phase Breast Pump with PersonalFit Flex',
    slug: 'medela-harmony-manual-breast-pump',
    categoryId: 'cat-mother-maternity',
    categoryName: 'Mother & Maternity',
    categorySlug: 'mother-maternity',
    subCategoryId: 'sub-nursing',
    subCategoryName: 'Breast Pumps & Nursing',
    brand: 'Medela',
    price: 3450,
    originalPrice: 4200,
    discount: 18,
    stock: 25,
    sku: 'MED-HAR-01',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop',
    ],
    description: 'Swiss-designed 2-Phase expression technology mimics a baby’s natural sucking rhythm. Lightweight, ergonomic and portable for mothers.',
    specifications: {
      'Origin': 'Switzerland',
      'Technology': '2-Phase Expression',
      'Shield': 'PersonalFit Flex 24mm',
    },
    badge: 'Essential',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 520,
  },
  {
    id: 'p-maternity-nursing-pillow',
    name: 'Ergonomic U-Shaped Full Body Maternity Pregnancy Pillow',
    slug: 'ergonomic-u-shaped-maternity-pillow',
    categoryId: 'cat-mother-maternity',
    categoryName: 'Mother & Maternity',
    categorySlug: 'mother-maternity',
    subCategoryId: 'sub-maternity-wear',
    subCategoryName: 'Maternity Wear',
    brand: 'Nurtura',
    price: 1750,
    originalPrice: 2400,
    discount: 27,
    stock: 40,
    sku: 'NUR-PIL-U',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&h=600&fit=crop'],
    description: 'Supports back, hips, knees, and belly during pregnancy and provides comfortable posture during breastfeeding. Washable 100% cotton velvet cover.',
    specifications: {
      'Shape': 'U-Shaped 55 Inch',
      'Cover': '100% Breathable Cotton',
      'Filling': 'Hypoallergenic Polyfill',
    },
    badge: 'Trending',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isActive: true,
    rating: 4.8,
    reviewCount: 215,
  },

  // 3. Men's Fashion
  {
    id: 'p-aarong-panjabi-white',
    name: 'Premium Jacquard Cotton Formal Panjabi (Off-White)',
    slug: 'premium-jacquard-cotton-panjabi-white',
    categoryId: 'cat-mens-fashion',
    categoryName: "Men's Fashion",
    categorySlug: 'mens-fashion',
    subCategoryId: 'sub-panjabi',
    subCategoryName: 'Panjabis & Kurtas',
    brand: 'Aarong',
    price: 2450,
    originalPrice: 3200,
    discount: 23,
    stock: 80,
    sku: 'AAR-PAN-WHT',
    image: 'https://images.unsplash.com/photo-1611608776653-f6110bb47067?w=600&h=600&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1611608776653-f6110bb47067?w=600&h=600&fit=crop',
    ],
    description: 'Exquisite jacquard woven fine Egyptian cotton Panjabi with hand-embroidered collar and cuffs. Perfect for Eid and celebrations.',
    specifications: {
      'Fabric': '100% Fine Combed Cotton',
      'Pattern': 'Jacquard Textured',
      'Collar': 'Mandarin with Hand Stitches',
    },
    badge: 'Eid Special',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.8,
    reviewCount: 684,
  },
  {
    id: 'p-yellow-denim-jeans',
    name: 'Yellow Slim Fit Stretch Denim Jeans (Dark Indigo)',
    slug: 'yellow-slim-fit-stretch-denim-jeans',
    categoryId: 'cat-mens-fashion',
    categoryName: "Men's Fashion",
    categorySlug: 'mens-fashion',
    subCategoryId: 'sub-jeans',
    subCategoryName: 'Jeans & Chinos',
    brand: 'Yellow',
    price: 1450,
    originalPrice: 1950,
    discount: 26,
    stock: 65,
    sku: 'YEL-DNM-IND',
    image: 'https://images.unsplash.com/photo-1674333162697-ccdde1ed4cca?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1674333162697-ccdde1ed4cca?w=600&h=600&fit=crop'],
    description: 'Durable and breathable 12oz denim with 2% elastane for maximum comfort and freedom of movement throughout the day.',
    specifications: {
      'Fit': 'Slim Fit',
      'Material': '98% Cotton, 2% Spandex',
      'Wash': 'Enzyme Stone Washed',
    },
    badge: 'Bestseller',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.6,
    reviewCount: 295,
  },

  // 4. Women's Fashion
  {
    id: 'p-silk-georgette-saree',
    name: 'Pure Georgette Jamdani Weave Saree with Zari Border (Crimson Red)',
    slug: 'georgette-jamdani-saree-crimson',
    categoryId: 'cat-womens-fashion',
    categoryName: "Women's Fashion",
    categorySlug: 'womens-fashion',
    subCategoryId: 'sub-sarees',
    subCategoryName: 'Silk & Cotton Sarees',
    brand: 'Aarong',
    price: 3600,
    originalPrice: 4800,
    discount: 25,
    stock: 35,
    sku: 'AAR-SAR-RED',
    image: 'https://images.unsplash.com/photo-1697020440966-ced476de15bd?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1697020440966-ced476de15bd?w=600&h=600&fit=crop'],
    description: 'Traditional Dhakai inspired Jamdani motif with metallic golden zari weaving on lightweight georgette silk. Comes with unstitched blouse piece.',
    specifications: {
      'Saree Length': '5.5 Meters + 0.8m Blouse Piece',
      'Fabric': 'Silk Georgette',
      'Occasion': 'Festive & Party',
    },
    badge: 'Eid Collection',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 412,
  },
  {
    id: 'p-cotton-kurti-set',
    name: 'Block Printed Organic Cotton Kurti with Palazzo Pants (Pastel Blue)',
    slug: 'block-printed-cotton-kurti-palazzo-blue',
    categoryId: 'cat-womens-fashion',
    categoryName: "Women's Fashion",
    categorySlug: 'womens-fashion',
    subCategoryId: 'sub-kurtis',
    subCategoryName: 'Kurtis & 3-Pieces',
    brand: 'Yellow',
    price: 1650,
    originalPrice: 2200,
    discount: 25,
    stock: 50,
    sku: 'YEL-KRT-BLU',
    image: 'https://images.unsplash.com/photo-1583710457367-47de0ea21fef?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1583710457367-47de0ea21fef?w=600&h=600&fit=crop'],
    description: 'Handcrafted floral wooden block prints on lightweight breathable organic cotton fabric. Styled with wide-leg palazzo trousers.',
    specifications: {
      'Set Includes': '1 Kurti, 1 Palazzo Pant',
      'Fabric': '100% Breathable Voile Cotton',
      'Fit': 'Comfort A-Line',
    },
    badge: 'Popular',
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    isActive: true,
    rating: 4.7,
    reviewCount: 184,
  },

  // 5. Electronics & Gadgets
  {
    id: 'p-anker-soundcore-r50i',
    name: 'Anker Soundcore R50i True Wireless Earbuds (10mm Bass, 30h Playtime)',
    slug: 'anker-soundcore-r50i-true-wireless',
    categoryId: 'cat-electronics',
    categoryName: 'Electronics & Gadgets',
    categorySlug: 'electronics-gadgets',
    subCategoryId: 'sub-audio',
    subCategoryName: 'Earbuds & Headphones',
    brand: 'Anker',
    price: 1750,
    originalPrice: 2300,
    discount: 24,
    stock: 90,
    sku: 'ANK-R50I-BLK',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop'],
    description: 'Crisp audio with oversized 10mm drivers, customized 22 EQ presets in the Soundcore app, IPX5 waterproof, and AI-enhanced clear calls.',
    specifications: {
      'Bluetooth': '5.3 with 10m Range',
      'Battery': '10h Single Playtime / 30h with Case',
      'Water Resistance': 'IPX5',
      'Warranty': '18 Months Official Brand Warranty',
    },
    badge: 'Hot Deal',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 1120,
  },
  {
    id: 'p-xiaomi-powerbank-20000',
    name: 'Xiaomi 20000mAh 22.5W Fast Charging Power Bank 3 (Dual USB-C Output)',
    slug: 'xiaomi-20000mah-22-5w-fast-powerbank',
    categoryId: 'cat-electronics',
    categoryName: 'Electronics & Gadgets',
    categorySlug: 'electronics-gadgets',
    subCategoryId: 'sub-chargers',
    subCategoryName: 'Power Banks & Cables',
    brand: 'Xiaomi',
    price: 2150,
    originalPrice: 2700,
    discount: 20,
    stock: 75,
    sku: 'MI-PB-20K',
    image: 'https://images.unsplash.com/photo-1609592426863-71866763a8a3?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1609592426863-71866763a8a3?w=600&h=600&fit=crop'],
    description: 'Triple-port simultaneous output with Quick Charge 3.0 and Power Delivery. Charges an iPhone or Galaxy up to 4-5 times on a single charge.',
    specifications: {
      'Capacity': '20,000 mAh (74Wh)',
      'Max Power': '22.5W Fast Charge',
      'Ports': '2x USB-A, 1x Type-C',
    },
    badge: 'Authentic',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 840,
  },

  // 6. Health & Beauty
  {
    id: 'p-garnier-vitamin-c',
    name: 'Garnier SkinActive 30x Booster Vitamin C Brightening Serum 30ml',
    slug: 'garnier-vitamin-c-brightening-serum-30ml',
    categoryId: 'cat-beauty',
    categoryName: 'Health & Beauty',
    categorySlug: 'health-beauty',
    subCategoryId: 'sub-skincare',
    subCategoryName: 'Face Serums & Creams',
    brand: 'Garnier',
    price: 780,
    originalPrice: 990,
    discount: 21,
    stock: 120,
    sku: 'GAR-VIT-C-30',
    image: 'https://images.unsplash.com/photo-1552819289-824d37ca69d2?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1552819289-824d37ca69d2?w=600&h=600&fit=crop'],
    description: 'Enriched with Yuzu lemon and 30x pure Vitamin C extract. Clinically proven to reduce dark spots and acne marks in just 3 days.',
    specifications: {
      'Volume': '30 ml',
      'Skin Type': 'All Skin Types (Dermatologically Tested)',
      'Effect': 'Brightening & Anti-Spot',
    },
    badge: 'Trending',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.6,
    reviewCount: 750,
  },

  // 7. Home & Kitchen
  {
    id: 'p-prestige-induction',
    name: 'Prestige PIC 6.0 V3 2000-Watt Digital Induction Cooktop',
    slug: 'prestige-pic-60-v3-induction-cooktop',
    categoryId: 'cat-home-kitchen',
    categoryName: 'Home & Kitchen',
    categorySlug: 'home-kitchen',
    subCategoryId: 'sub-cookware',
    subCategoryName: 'Cookware & Cooktops',
    brand: 'Prestige',
    price: 3850,
    originalPrice: 4700,
    discount: 18,
    stock: 28,
    sku: 'PRS-IND-2000',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=600&fit=crop'],
    description: 'High energy efficiency induction cooker with pre-programmed Indian & Bengali cooking modes (Curry, Roti, Dosa, Milk). Automatic voltage regulator.',
    specifications: {
      'Power': '2000 Watts',
      'Display': 'Digital LED with Touch Timer',
      'Glass': 'Full Crystal Ceramic Plate',
    },
    badge: 'Energy Saver',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 340,
  },

  // 8. Food & Grocery
  {
    id: 'p-aci-pure-basmati',
    name: 'ACI Pure Traditional Basmati Rice 5kg (Aged 2 Years)',
    slug: 'aci-pure-basmati-rice-5kg',
    categoryId: 'cat-food-grocery',
    categoryName: 'Food & Grocery',
    categorySlug: 'food-grocery',
    subCategoryId: 'sub-staples',
    subCategoryName: 'Rice, Spices & Staples',
    brand: 'ACI Pure',
    price: 890,
    originalPrice: 1050,
    discount: 15,
    stock: 150,
    sku: 'ACI-BAS-5KG',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&h=600&fit=crop'],
    description: 'Extra long grain aged Himalayan basmati rice. Fluffy and aromatic, elongates twice its size when cooked. 100% natural and unpolished.',
    specifications: {
      'Net Weight': '5 KG',
      'Aging': '2 Years Aged',
      'Grain Length': '8.3mm+ After Cooking',
    },
    badge: 'Fresh Stock',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 1420,
  },
  {
    id: 'p-sundarban-raw-honey',
    name: 'Sundarban Raw Wild Forest Honey (Khalisha Flower, 500g)',
    slug: 'sundarban-raw-wild-honey-500g',
    categoryId: 'cat-food-grocery',
    categoryName: 'Food & Grocery',
    categorySlug: 'food-grocery',
    subCategoryId: 'sub-organic',
    subCategoryName: 'Organic Honey & Ghee',
    brand: 'Sundarban Organic',
    price: 650,
    originalPrice: 850,
    discount: 24,
    stock: 90,
    sku: 'SUN-HNY-500',
    image: 'https://images.unsplash.com/photo-1586208958839-06c17cacdf08?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1586208958839-06c17cacdf08?w=600&h=600&fit=crop'],
    description: '100% raw unheated and unfiltered honey sustainably harvested from wild mangrove beehives in the Sundarbans. Packed with natural enzymes.',
    specifications: {
      'Weight': '500 Grams',
      'Purity': '100% Unprocessed Wild Honey',
      'Origin': 'Sundarbans, Bangladesh',
    },
    badge: '100% Pure',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 460,
  },
];

export const INITIAL_BANNERS: BannerItem[] = [
  {
    id: 'b-1',
    title: 'Celebrate Eid with Premium Collections',
    subtitle: 'Exclusive discounts on Men’s Panjabis, Women’s Sarees & Lifestyle Gadgets',
    badge: 'Mega Eid Festival 2026',
    ctaText: 'Explore Collection',
    ctaLink: '/category/mens-fashion',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1600&h=600&fit=crop',
    order: 1,
    isActive: true,
  },
  {
    id: 'b-2',
    title: 'Complete Baby Care & Maternity Essentials',
    subtitle: 'Top global brands: Pampers, Medela, Aveeno & Dr. Brown’s at trusted prices',
    badge: '100% Authentic Guarantee',
    ctaText: 'Shop Baby & Mother',
    ctaLink: '/category/baby-kids',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=1600&h=600&fit=crop',
    order: 2,
    isActive: true,
  },
  {
    id: 'b-3',
    title: 'Modern Electronics & Smart Life Gadgets',
    subtitle: 'Fast charging power banks, true wireless earbuds, and everyday accessories',
    badge: 'Official Warranty',
    ctaText: 'Browse Gadgets',
    ctaLink: '/category/electronics-gadgets',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1600&h=600&fit=crop',
    order: 3,
    isActive: true,
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 'c-welcome',
    code: 'WELCOME10',
    type: 'PERCENTAGE',
    value: 10,
    minOrder: 1000,
    maxDiscount: 300,
    usedCount: 14,
    isActive: true,
  },
  {
    id: 'c-eid2026',
    code: 'EID2026',
    type: 'FIXED',
    value: 200,
    minOrder: 2500,
    usedCount: 42,
    isActive: true,
  },
];

export const INITIAL_REVIEWS = [
  {
    id: 'r1',
    name: 'Tasnim Akter',
    location: 'Dhanmondi, Dhaka',
    rating: 5,
    date: '02 Mar 2026',
    comment: 'Super fast delivery to Dhaka! Got the Pampers diapers and Aveeno wash within 24 hours. Well packaged and 100% original.',
    verified: true,
    avatar: 'TA',
  },
  {
    id: 'r2',
    name: 'Roksana Begum',
    location: 'Chittagong City',
    rating: 5,
    date: '28 Feb 2026',
    comment: 'Ordered the Aarong Saree for my family. The zari work is gorgeous, exactly as displayed on the website. Very happy with the cash on delivery service.',
    verified: true,
    avatar: 'RB',
  },
  {
    id: 'r3',
    name: 'Mahmud Hossain',
    location: 'Sylhet Sadar',
    rating: 5,
    date: '25 Feb 2026',
    comment: 'Bought the U-shaped pregnancy pillow for my wife. It relieved her back pain immediately. Customer support via hotline was exceptionally polite!',
    verified: true,
    avatar: 'MH',
  },
  {
    id: 'r4',
    name: 'Karim Uddin',
    location: 'Uttara, Dhaka',
    rating: 5,
    date: '20 Feb 2026',
    comment: 'Paid with bKash Send Money. The verification was confirmed within 15 minutes and the Panjabi arrived the next morning. Highly recommended!',
    verified: true,
    avatar: 'KU',
  },
];
