import { CategoryItem, ProductItem, BannerItem, CouponItem, StoreSettings } from './types';

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: 'Jawata Mart',
  tagline: 'Your Trusted Online Shopping Destination in Bangladesh',
  phone: '01915210799',
  email: 'jawatamart@gmail.com',
  address: 'Uttara Sector-12, Dhaka, Bangladesh',
  bkashMerchantNumber: '01915210799',
  nagadMerchantNumber: '01915210799',
  insideDhakaFee: 60,
  outsideDhakaFee: 120,
  freeDeliveryThreshold: 2000,
  sslcommerzStoreId: process.env.SSLCOMMERZ_STORE_ID || 'testbox',
  sslcommerzIsLive: process.env.SSLCOMMERZ_IS_LIVE === 'true',
};

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-bag',
    name: 'Bag',
    slug: 'bag',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    description: 'School bags, kids backpacks, elegant ladies handbags, and durable travelling bags.',
    icon: 'Briefcase',
    isFeatured: true,
    order: 1,
    isActive: true,
    subCategories: [
      { id: 'sub-school-bag', categoryId: 'cat-bag', name: 'School Bag', slug: 'school-bag', order: 1 },
      { id: 'sub-kids-bag', categoryId: 'cat-bag', name: 'Kids Bag', slug: 'kids-bag', order: 2 },
      { id: 'sub-ladies-bag', categoryId: 'cat-bag', name: 'Ladies Bag', slug: 'ladies-bag', order: 3 },
      { id: 'sub-travelling-bag', categoryId: 'cat-bag', name: 'Travelling Bag', slug: 'travelling-bag', order: 4 },
    ],
  },
  {
    id: 'cat-kids-toys',
    name: 'Kids Toys',
    slug: 'kids-toys',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=600&fit=crop',
    description: 'Montessori educational toys, high-speed remote control cars, plush dolls, and outdoor games.',
    icon: 'Gamepad2',
    isFeatured: true,
    order: 2,
    isActive: true,
    subCategories: [
      { id: 'sub-educational-toys', categoryId: 'cat-kids-toys', name: 'Educational Toys', slug: 'educational-toys', order: 1 },
      { id: 'sub-rc-cars', categoryId: 'cat-kids-toys', name: 'Remote Control & Cars', slug: 'rc-cars', order: 2 },
      { id: 'sub-dolls-soft-toys', categoryId: 'cat-kids-toys', name: 'Dolls & Soft Toys', slug: 'dolls-soft-toys', order: 3 },
      { id: 'sub-outdoor-toys', categoryId: 'cat-kids-toys', name: 'Outdoor & Sports Toys', slug: 'outdoor-toys', order: 4 },
    ],
  },
  {
    id: 'cat-baby-dress',
    name: 'Baby Dress',
    slug: 'baby-dress',
    image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600&h=600&fit=crop',
    description: '100% organic cotton newborn clothes, stylish baby boys and girls party dresses, and comfortable rompers.',
    icon: 'Baby',
    isFeatured: true,
    order: 3,
    isActive: true,
    subCategories: [
      { id: 'sub-newborn-clothes', categoryId: 'cat-baby-dress', name: 'Newborn Clothes', slug: 'newborn-clothes', order: 1 },
      { id: 'sub-baby-boys-dress', categoryId: 'cat-baby-dress', name: 'Baby Boys Dress', slug: 'baby-boys-dress', order: 2 },
      { id: 'sub-baby-girls-dress', categoryId: 'cat-baby-dress', name: 'Baby Girls Dress', slug: 'baby-girls-dress', order: 3 },
      { id: 'sub-rompers-sets', categoryId: 'cat-baby-dress', name: 'Rompers & Sets', slug: 'rompers-sets', order: 4 },
    ],
  },
  {
    id: 'cat-baby-shoes',
    name: 'Baby Shoes',
    slug: 'baby-shoes',
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&h=600&fit=crop',
    description: 'Anti-slip soft sole infant booties, baby boy formal shoes, princess girl shoes, and toddler sneakers.',
    icon: 'Footprints',
    isFeatured: true,
    order: 4,
    isActive: true,
    subCategories: [
      { id: 'sub-soft-sole-booties', categoryId: 'cat-baby-shoes', name: 'Soft Sole Booties', slug: 'soft-sole-booties', order: 1 },
      { id: 'sub-baby-boy-shoes', categoryId: 'cat-baby-shoes', name: 'Baby Boy Shoes', slug: 'baby-boy-shoes', order: 2 },
      { id: 'sub-baby-girl-shoes', categoryId: 'cat-baby-shoes', name: 'Baby Girl Shoes', slug: 'baby-girl-shoes', order: 3 },
      { id: 'sub-toddler-sneakers', categoryId: 'cat-baby-shoes', name: 'Toddler Sneakers & Sandals', slug: 'toddler-sneakers', order: 4 },
    ],
  },
  {
    id: 'cat-cosmetics-items',
    name: 'Cosmetics Items (Baby & Parents)',
    slug: 'cosmetics-items',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop',
    description: 'Safe organic baby wash, tear-free shampoos, postpartum mother care essentials, and skincare.',
    icon: 'Sparkles',
    isFeatured: true,
    order: 5,
    isActive: true,
    subCategories: [
      { id: 'sub-baby-skincare-wash', categoryId: 'cat-cosmetics-items', name: 'Baby Skincare & Wash', slug: 'baby-skincare-wash', order: 1 },
      { id: 'sub-mother-care', categoryId: 'cat-cosmetics-items', name: 'Mother Care & Postpartum', slug: 'mother-care', order: 2 },
      { id: 'sub-organic-hair-care', categoryId: 'cat-cosmetics-items', name: 'Organic Hair Care', slug: 'organic-hair-care', order: 3 },
      { id: 'sub-fragrance-glow', categoryId: 'cat-cosmetics-items', name: 'Fragrance & Glow', slug: 'fragrance-glow', order: 4 },
    ],
  },
  {
    id: 'cat-gift-item',
    name: 'Gift Item',
    slug: 'gift-item',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600&h=600&fit=crop',
    description: 'Thoughtful birthday surprise boxes, baby shower combo packs, Islamic gift boxes, and corporate tokens.',
    icon: 'Gift',
    isFeatured: true,
    order: 6,
    isActive: true,
    subCategories: [
      { id: 'sub-birthday-gifts', categoryId: 'cat-gift-item', name: 'Birthday Gifts', slug: 'birthday-gifts', order: 1 },
      { id: 'sub-baby-shower-combos', categoryId: 'cat-gift-item', name: 'Baby Shower Combos', slug: 'baby-shower-combos', order: 2 },
      { id: 'sub-islamic-gift-sets', categoryId: 'cat-gift-item', name: 'Islamic Gift Sets', slug: 'islamic-gift-sets', order: 3 },
      { id: 'sub-custom-gifts', categoryId: 'cat-gift-item', name: 'Corporate & Custom Gifts', slug: 'custom-gifts', order: 4 },
    ],
  },
  {
    id: 'cat-home-tex',
    name: 'Home Tex',
    slug: 'home-tex',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&h=600&fit=crop',
    description: 'Cotton bath towels, luxury living room curtains, decorative cushion covers, and dining table runners.',
    icon: 'Home',
    isFeatured: true,
    order: 7,
    isActive: true,
    subCategories: [
      { id: 'sub-towels-bath-mats', categoryId: 'cat-home-tex', name: 'Towels & Bath Mats', slug: 'towels-bath-mats', order: 1 },
      { id: 'sub-curtains-drapes', categoryId: 'cat-home-tex', name: 'Curtains & Drapes', slug: 'curtains-drapes', order: 2 },
      { id: 'sub-cushion-covers', categoryId: 'cat-home-tex', name: 'Cushion & Pillow Covers', slug: 'cushion-covers', order: 3 },
      { id: 'sub-table-linens', categoryId: 'cat-home-tex', name: 'Table Linens & Mats', slug: 'table-linens', order: 4 },
    ],
  },
  {
    id: 'cat-bed-sheet',
    name: 'Bed Sheet',
    slug: 'bed-sheet',
    image: 'https://images.unsplash.com/photo-1629949009765-40fc74c95018?w=600&h=600&fit=crop',
    description: '100% pure cotton king and queen bedsheets, single bed sheets, floral prints, and cozy comforters.',
    icon: 'Layers',
    isFeatured: true,
    order: 8,
    isActive: true,
    subCategories: [
      { id: 'sub-single-bed-sheets', categoryId: 'cat-bed-sheet', name: 'Single Bed Sheets', slug: 'single-bed-sheets', order: 1 },
      { id: 'sub-double-king-bed-sheets', categoryId: 'cat-bed-sheet', name: 'Double & King Bed Sheets', slug: 'double-king-bed-sheets', order: 2 },
      { id: 'sub-cotton-printed-bedsheets', categoryId: 'cat-bed-sheet', name: '100% Cotton Printed', slug: 'cotton-printed-bedsheets', order: 3 },
      { id: 'sub-comforters-blankets', categoryId: 'cat-bed-sheet', name: 'Comforters & Blankets', slug: 'comforters-blankets', order: 4 },
    ],
  },
  {
    id: 'cat-educational-items',
    name: 'Educational Items',
    slug: 'educational-items',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=600&fit=crop',
    description: 'Child-friendly Islamic & moral storybooks, brain puzzle flashcards, art supplies, and Montessori gear.',
    icon: 'BookOpen',
    isFeatured: true,
    order: 9,
    isActive: true,
    subCategories: [
      { id: 'sub-islamic-general-books', categoryId: 'cat-educational-items', name: 'Islamic & General Books', slug: 'islamic-general-books', order: 1 },
      { id: 'sub-flashcards-puzzles', categoryId: 'cat-educational-items', name: 'Learning Flashcards & Puzzles', slug: 'flashcards-puzzles', order: 2 },
      { id: 'sub-writing-art-supplies', categoryId: 'cat-educational-items', name: 'Writing & Art Supplies', slug: 'writing-art-supplies', order: 3 },
      { id: 'sub-montessori-tools', categoryId: 'cat-educational-items', name: 'Montessori Tools', slug: 'montessori-tools', order: 4 },
    ],
  },
  {
    id: 'cat-kitchen-items',
    name: 'Kitchen Items',
    slug: 'kitchen-items',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&h=600&fit=crop',
    description: 'Granite non-stick cookware pots, airtight glass organizers, stainless cutlery, and baby food silicone bowls.',
    icon: 'Utensils',
    isFeatured: true,
    order: 10,
    isActive: true,
    subCategories: [
      { id: 'sub-cookware-pots', categoryId: 'cat-kitchen-items', name: 'Cookware & Pots', slug: 'cookware-pots', order: 1 },
      { id: 'sub-kitchen-storage', categoryId: 'cat-kitchen-items', name: 'Kitchen Storage & Organizers', slug: 'kitchen-storage', order: 2 },
      { id: 'sub-cutlery-dinnerware', categoryId: 'cat-kitchen-items', name: 'Cutlery & Dinnerware', slug: 'cutlery-dinnerware', order: 3 },
      { id: 'sub-baby-dining', categoryId: 'cat-kitchen-items', name: 'Silicone & Baby Dining', slug: 'baby-dining', order: 4 },
    ],
  },
  {
    id: 'cat-health-skin-care',
    name: 'Health Care & Skin Care Items',
    slug: 'health-skin-care',
    image: 'https://images.unsplash.com/photo-1552819289-824d37ca69d2?w=600&h=600&fit=crop',
    description: 'Herbal face wash, brightening serums, cold-pressed hair growth oils, sunscreen, and daily vitamins.',
    icon: 'HeartPulse',
    isFeatured: true,
    order: 11,
    isActive: true,
    subCategories: [
      { id: 'sub-organic-face-care', categoryId: 'cat-health-skin-care', name: 'Organic Face Care', slug: 'organic-face-care', order: 1 },
      { id: 'sub-natural-hair-oils', categoryId: 'cat-health-skin-care', name: 'Natural Hair Oils', slug: 'natural-hair-oils', order: 2 },
      { id: 'sub-sunscreens-moisturizers', categoryId: 'cat-health-skin-care', name: 'Sunscreens & Moisturizers', slug: 'sunscreens-moisturizers', order: 3 },
      { id: 'sub-wellness-supplements', categoryId: 'cat-health-skin-care', name: 'Wellness Supplements', slug: 'wellness-supplements', order: 4 },
    ],
  },
  {
    id: 'cat-islamic-items',
    name: 'Islamic Items',
    slug: 'islamic-items',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&h=600&fit=crop',
    description: 'Tajweed Quran with wooden Rehal, luxury velvet prayer mats, alcohol-free Attar, and crystal Tasbeeh.',
    icon: 'Moon',
    isFeatured: true,
    order: 12,
    isActive: true,
    subCategories: [
      { id: 'sub-quran-rehal', categoryId: 'cat-islamic-items', name: 'Quran & Rehal', slug: 'quran-rehal', order: 1 },
      { id: 'sub-janamaz-prayer-mats', categoryId: 'cat-islamic-items', name: 'Premium Janamaz (Prayer Mats)', slug: 'janamaz-prayer-mats', order: 2 },
      { id: 'sub-attar-tasbeeh', categoryId: 'cat-islamic-items', name: 'Attar & Tasbeeh', slug: 'attar-tasbeeh', order: 3 },
      { id: 'sub-islamic-books-caps', categoryId: 'cat-islamic-items', name: 'Islamic Books & Caps', slug: 'islamic-books-caps', order: 4 },
    ],
  },
  {
    id: 'cat-winter-items',
    name: 'Winter Items',
    slug: 'winter-items',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop',
    description: 'Baby fleece hoodies, thermal inner wear, Kashmiri shawls, thick winter blankets, and wool caps.',
    icon: 'Snowflake',
    isFeatured: true,
    order: 13,
    isActive: true,
    subCategories: [
      { id: 'sub-baby-winter-sweaters', categoryId: 'cat-winter-items', name: 'Baby Winter Sweaters & Hoodies', slug: 'baby-winter-sweaters', order: 1 },
      { id: 'sub-shawls-wraps', categoryId: 'cat-winter-items', name: 'Shawls & Wraps', slug: 'shawls-wraps', order: 2 },
      { id: 'sub-quilts-blankets', categoryId: 'cat-winter-items', name: 'Blankets & Quilts', slug: 'quilts-blankets', order: 3 },
      { id: 'sub-winter-caps-socks', categoryId: 'cat-winter-items', name: 'Winter Caps & Socks', slug: 'winter-caps-socks', order: 4 },
    ],
  },
  {
    id: 'cat-weather-items',
    name: 'Weather & Umbrella',
    slug: 'weather-items',
    image: '/uploads/clean/1789051394753.jpg',
    description: 'High quality windproof umbrellas, transparent dome umbrellas, UV sun protection gear, and waterproof raincoats.',
    icon: 'CloudRain',
    isFeatured: true,
    order: 14,
    isActive: true,
    subCategories: [
      { id: 'sub-umbrellas', categoryId: 'cat-weather-items', name: 'Umbrellas & Parasols', slug: 'umbrellas', order: 1 },
      { id: 'sub-kids-rainwear', categoryId: 'cat-weather-items', name: 'Kids Rainwear & Raincoats', slug: 'raincoats', order: 2 },
      { id: 'sub-uv-sun-shield', categoryId: 'cat-weather-items', name: 'UV Sun Protection', slug: 'sun-protection', order: 3 },
    ],
  },
];
export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    "id": "p-drv-bag-hellokitty-school",
    "name": "Hello Kitty Cute Velvet Toddler Backpack (Pink & White)",
    "slug": "hello-kitty-cute-velvet-toddler-backpack",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-kids-bag",
    "subCategoryName": "Kids Bag",
    "subCategorySlug": "kids-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 50,
    "sku": "JM-BAG-HK-01",
    "image": "/uploads/clean/1789051394558.jpg",
    "images": [
      "/uploads/clean/1789051394558.jpg",
      "/uploads/clean/1789051394470.jpg"
    ],
    "description": "Ultra-soft premium plush velvet Hello Kitty kids school and travel backpack with front zip pocket and soft padded straps.",
    "specifications": {
      "Material": "Soft Velvet Plush",
      "Compartments": "Main Zipper + Front Pouch",
      "Origin": "Imported"
    },
    "badge": "Popular",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 38
  },
  {
    "id": "p-drv-bag-hellokitty-plush",
    "name": "Preschool Hello Kitty Soft Plush Bag with Bow",
    "slug": "preschool-hello-kitty-soft-plush-bag-with-bow",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-kids-bag",
    "subCategoryName": "Kids Bag",
    "subCategorySlug": "kids-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 45,
    "sku": "JM-BAG-HK-02",
    "image": "/uploads/clean/1789051394470.jpg",
    "images": [
      "/uploads/clean/1789051394470.jpg"
    ],
    "description": "Adorably designed Hello Kitty preschool bag for toddlers and young girls. Lightweight, durable, and comfortable for little shoulders.",
    "specifications": {
      "Material": "Plush Velvet",
      "Color": "Pastel Pink",
      "Type": "Toddler Backpack"
    },
    "badge": "New Arrival",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 24
  },
  {
    "id": "p-drv-bag-primary-waterproof",
    "name": "Multi-Compartment Waterproof Primary School Backpack with Doll (Pink)",
    "slug": "multi-compartment-waterproof-primary-school-backpack",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-school-bag",
    "subCategoryName": "School Bag",
    "subCategorySlug": "school-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 60,
    "sku": "JM-BAG-SCH-01",
    "image": "/uploads/clean/1789051394438.jpg",
    "images": [
      "/uploads/clean/1789051394438.jpg"
    ],
    "description": "Spacious waterproof kids bookbag with cute animal badges, hanging pom-pom charm, and ergonomic spine protection back cushioning.",
    "specifications": {
      "Waterproof": "Yes (Oxford Nylon)",
      "Closure": "Heavy Duty Zippers",
      "Includes": "Cute Hanging Fur Ball"
    },
    "badge": "Best Seller",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 52
  },
  {
    "id": "p-drv-bag-ortho-jincaizi",
    "name": "Jincaizi Huang Orthopedic Ergonomic Student Backpack (Mint Green)",
    "slug": "jincaizi-huang-orthopedic-student-backpack",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-school-bag",
    "subCategoryName": "School Bag",
    "subCategorySlug": "school-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 40,
    "sku": "JM-BAG-SCH-02",
    "image": "/uploads/clean/1789051394500.jpg",
    "images": [
      "/uploads/clean/1789051394500.jpg"
    ],
    "description": "High quality premium pastel school bag with multi-layer organizer pockets, safety reflective trims, and breathable mesh back pads.",
    "specifications": {
      "Design": "Ergonomic Weight Balancing",
      "Fabric": "High Density Polyester",
      "Color": "Mint Green / Pink"
    },
    "badge": "Editor Pick",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 19
  },
  {
    "id": "p-drv-bag-korean-cute-school",
    "name": "Korean Aesthetic College & School Backpack with Duck Plush Charm",
    "slug": "korean-aesthetic-college-school-backpack",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-school-bag",
    "subCategoryName": "School Bag",
    "subCategorySlug": "school-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 55,
    "sku": "JM-BAG-SCH-03",
    "image": "/uploads/clean/1789051394588.jpg",
    "images": [
      "/uploads/clean/1789051394588.jpg"
    ],
    "description": "Trendy Korean style beige canvas backpack with cute duck plush pendant, large capacity for 15.6 inch laptop, and multiple utility pockets.",
    "specifications": {
      "Capacity": "Fits A4 Books & 15.6 Laptop",
      "Pockets": "5 External + 1 Main",
      "Accessories": "Includes Plush Duck"
    },
    "badge": "Trending",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 42
  },
  {
    "id": "p-drv-bag-cuvea-travel-duffel",
    "name": "Cuvea Korres Multi-Pocket Travel Duffel & Gym Bag with Shoe Compartment",
    "slug": "cuvea-korres-travel-duffel-gym-bag",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-travelling-bag",
    "subCategoryName": "Travelling Bag",
    "subCategorySlug": "travelling-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 65,
    "sku": "JM-BAG-TRV-01",
    "image": "/uploads/clean/1789051394201.jpg",
    "images": [
      "/uploads/clean/1789051394201.jpg",
      "/uploads/clean/1789051394236.jpg",
      "/uploads/clean/1789051394270.jpg",
      "/uploads/clean/1789051394302.jpg",
      "/uploads/clean/1789051394330.jpg",
      "/uploads/clean/1789051394357.jpg",
      "/uploads/clean/1789051394383.jpg",
      "/uploads/clean/1789051394408.jpg"
    ],
    "description": "Spacious waterproof travel cylinder duffel bag featuring independent ventilated shoe pouch, dry/wet separation pocket, and adjustable padded shoulder strap.",
    "specifications": {
      "Dimensions": "38cm x 22cm x 22cm",
      "Weight": "0.42kg",
      "Material": "Oxford Water-repellent Fabric",
      "Colors": "Blue, Black, Lilac, Yellow, Mint"
    },
    "badge": "Must Have",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 67
  },
  {
    "id": "p-drv-bag-3pc-ladies-set",
    "name": "Luxury 3-in-1 Ladies Backpack, Round Crossbody & Card Wallet Set (Pink)",
    "slug": "luxury-3-in-1-ladies-backpack-crossbody-wallet-set",
    "categoryId": "cat-bag",
    "categoryName": "Bag",
    "categorySlug": "bag",
    "subCategoryId": "sub-ladies-bag",
    "subCategoryName": "Ladies Bag",
    "subCategorySlug": "ladies-bag",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 35,
    "sku": "JM-BAG-LAD-01",
    "image": "/uploads/clean/1789051394530.jpg",
    "images": [
      "/uploads/clean/1789051394530.jpg"
    ],
    "description": "Stunning 3-piece combo set including a faux leather mini backpack with floral strap details, round chain crossbody bag, and matching clutch wallet.",
    "specifications": {
      "Pieces": "3 Pcs Set",
      "Material": "Premium PU Leather",
      "Features": "Teddy Bear Keychain Included"
    },
    "badge": "Combo Offer",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 31
  },
  {
    "id": "p-drv-toy-diecast-cars-pack",
    "name": "Diecast Alloy Pull-Back Mini Racing Cars Collection (Pack of 6)",
    "slug": "diecast-alloy-mini-racing-cars-pack-of-6",
    "categoryId": "cat-kids-toys",
    "categoryName": "Kids Toys",
    "categorySlug": "kids-toys",
    "subCategoryId": "sub-rc-cars",
    "subCategoryName": "Remote Control & Cars",
    "subCategorySlug": "rc-cars",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 50,
    "sku": "JM-TOY-CAR-01",
    "image": "/uploads/clean/1789051394972.jpg",
    "images": [
      "/uploads/clean/1789051394972.jpg",
      "/uploads/clean/1789051394824.jpg"
    ],
    "description": "High-speed metal alloy diecast miniature racing cars with authentic details and smooth pull-back mechanism. Perfect birthday gift for car lovers.",
    "specifications": {
      "Quantity": "6 Realistic Model Cars",
      "Material": "Metal Alloy + ABS Body",
      "Scale": "1:64"
    },
    "badge": "Kid Favorite",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 45
  },
  {
    "id": "p-drv-toy-scale-figures-city",
    "name": "Miniature Architectural City Diorama People & Street Figures Set",
    "slug": "miniature-diorama-people-street-figures-set",
    "categoryId": "cat-kids-toys",
    "categoryName": "Kids Toys",
    "categorySlug": "kids-toys",
    "subCategoryId": "sub-educational-toys",
    "subCategoryName": "Educational Toys",
    "subCategorySlug": "educational-toys",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 40,
    "sku": "JM-TOY-FIG-01",
    "image": "/uploads/clean/1789051395002.jpg",
    "images": [
      "/uploads/clean/1789051395002.jpg",
      "/uploads/clean/1789051395033.jpg",
      "/uploads/clean/1789051394824.jpg"
    ],
    "description": "Hand-painted miniature figurines for school science projects, scale models, train sets, and creative world-building play.",
    "specifications": {
      "Scale": "1:87 / HO Scale",
      "Material": "Safe Non-Toxic Resin",
      "Features": "30+ Hand Painted Mini People"
    },
    "badge": "Educational",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 22
  },
  {
    "id": "p-drv-toy-plush-bunny-trio",
    "name": "Super Soft Plush Cuddly Bunny Rabbit Dolls (Pink, Cream & White)",
    "slug": "super-soft-plush-cuddly-bunny-rabbit-dolls",
    "categoryId": "cat-kids-toys",
    "categoryName": "Kids Toys",
    "categorySlug": "kids-toys",
    "subCategoryId": "sub-dolls-soft-toys",
    "subCategoryName": "Dolls & Soft Toys",
    "subCategorySlug": "dolls-soft-toys",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 55,
    "sku": "JM-TOY-BUN-01",
    "image": "/uploads/clean/1789051394859.jpg",
    "images": [
      "/uploads/clean/1789051394859.jpg"
    ],
    "description": "Ultra-cuddly huggable bunny rabbits made from hypoallergenic microfleece. Safe for newborns, toddlers, and nursery room decor.",
    "specifications": {
      "Height": "25cm",
      "Fabric": "Hypoallergenic Soft Plush",
      "Washable": "Machine Washable"
    },
    "badge": "Ultra Soft",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 57
  },
  {
    "id": "p-drv-bdr-crochet-white-dress",
    "name": "Handmade Crochet Baby Girl Layered White Dress with Straw Hat & Shoes",
    "slug": "handmade-crochet-baby-girl-white-dress-set",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 30,
    "sku": "JM-BDR-CR-01",
    "image": "/uploads/clean/1789051393254.jpg",
    "images": [
      "/uploads/clean/1789051393254.jpg",
      "/uploads/clean/1789051393352.jpg"
    ],
    "description": "Exquisite 3-piece handmade crochet outfit featuring ruffle skirt frock, floral accent sunhat, and matching booties. Ideal for baby photography and celebrations.",
    "specifications": {
      "Pieces": "Dress + Sunhat + Booties",
      "Yarn": "100% Breathable Soft Cotton Yarn",
      "Care": "Hand Wash Cold"
    },
    "badge": "Handmade",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 64
  },
  {
    "id": "p-drv-bdr-bunny-knit-romper",
    "name": "Cozy Knitted Bunny Ear Hooded Romper Jumpsuit with Tail",
    "slug": "cozy-knitted-bunny-hooded-romper-jumpsuit",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 45,
    "sku": "JM-BDR-ROMP-01",
    "image": "/uploads/clean/1789051393278.jpg",
    "images": [
      "/uploads/clean/1789051393278.jpg"
    ],
    "description": "Charming warm knitted winter romper jumpsuit with floppy 3D bunny ears, wooden front buttons, and adorable white pompom tail on the back.",
    "specifications": {
      "Material": "Knitted Wool Blend",
      "Design": "3D Rabbit Ears Hood + Paws",
      "Sizes": "0-6M, 6-12M, 12-18M"
    },
    "badge": "Cutest Pick",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 48
  },
  {
    "id": "p-drv-bdr-crochet-pink-floral",
    "name": "Pink & White Hand-Knit Floral Baby Frock with Bow Headband & Booties",
    "slug": "pink-white-hand-knit-floral-baby-frock",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 35,
    "sku": "JM-BDR-CR-02",
    "image": "/uploads/clean/1789051393299.jpg",
    "images": [
      "/uploads/clean/1789051393299.jpg"
    ],
    "description": "Delightful handcrafted crochet princess dress adorned with 3D handmade flowers at the waistline, coordinating bow headband, and matching baby socks.",
    "specifications": {
      "Items": "Frock + Headband + Baby Shoes",
      "Yarn": "Pure Combed Cotton Yarn",
      "Craft": "100% Artisanal Handmade"
    },
    "badge": "Artisanal",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 29
  },
  {
    "id": "p-drv-bdr-peach-organza-dress",
    "name": "Peach Blossom Fairy Organza Baby Dress with Rosette Headband",
    "slug": "peach-blossom-fairy-organza-baby-dress",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 25,
    "sku": "JM-BDR-ORG-01",
    "image": "/uploads/clean/1789051393323.jpg",
    "images": [
      "/uploads/clean/1789051393323.jpg"
    ],
    "description": "Dreamy off-shoulder layered tulle organza birthday dress with delicate floral fabric headband. Designed for delicate newborn and toddler skin.",
    "specifications": {
      "Lining": "100% Pure Soft Cotton",
      "Outer": "Featherlight Organza",
      "Occasion": "Birthday & Photo Sessions"
    },
    "badge": "Special Occasion",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 33
  },
  {
    "id": "p-drv-bdr-pink-hearts-frock",
    "name": "Crochet Baby Girl Collar Dress with Pink Embroidered Hearts",
    "slug": "crochet-baby-girl-collar-dress-with-pink-hearts",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 40,
    "sku": "JM-BDR-CR-03",
    "image": "/uploads/clean/1789051393383.jpg",
    "images": [
      "/uploads/clean/1789051393383.jpg"
    ],
    "description": "Lovely Peter Pan collar woolen crochet baby frock patterned with all-over pastel pink hearts and decorative button placket.",
    "specifications": {
      "Pattern": "Handmade Hearts Embroidery",
      "Collar": "Ruffled Peter Pan Collar",
      "Includes": "Mini Matching Heart Charm"
    },
    "badge": "Cute Hearts",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 47
  },
  {
    "id": "p-drv-bdr-magenta-flower-frock",
    "name": "Magenta & White Lace Trim Handcrafted Baby Frock with Pearl Headband",
    "slug": "magenta-white-lace-trim-handcrafted-baby-frock",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 30,
    "sku": "JM-BDR-CR-04",
    "image": "/uploads/clean/1789051393410.jpg",
    "images": [
      "/uploads/clean/1789051393410.jpg"
    ],
    "description": "Bright magenta floral lace design crochet frock featuring beaded flower brooch, hanging pompom tassel strings, and pearl floral shoes.",
    "specifications": {
      "Yarn": "Skin-friendly Milk Cotton",
      "Details": "Tassel Pompoms & Pearl Center",
      "Set Includes": "Frock, Headband, Booties"
    },
    "badge": "Artisan Choice",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 26
  },
  {
    "id": "p-drv-bdr-purple-bloomer-suit",
    "name": "Royal Purple & White 4-Piece Crochet Frock, Bloomers, Bag & Booties",
    "slug": "royal-purple-crochet-frock-bloomers-bag-booties-set",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 35,
    "sku": "JM-BDR-CR-05",
    "image": "/uploads/clean/1789051393436.jpg",
    "images": [
      "/uploads/clean/1789051393436.jpg",
      "/uploads/clean/1789051393469.jpg"
    ],
    "description": "Premium 4-piece luxury handmade crochet ensemble: floral bow dress, ruffled bloomer shorts, mini purse, and ribbon-tied baby shoes.",
    "specifications": {
      "Pieces Included": "Dress + Bloomers + Mini Bag + Shoes + Headband",
      "Yarn": "Premium Soft Acrylic & Cotton",
      "Color": "Royal Purple / White"
    },
    "badge": "Luxury 4-in-1",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 51
  },
  {
    "id": "p-drv-bdr-sage-green-suit",
    "name": "Pastel Sage Green & White 4-Piece Crochet Frock & Shorts Set",
    "slug": "pastel-sage-green-crochet-frock-shorts-set",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 28,
    "sku": "JM-BDR-CR-06",
    "image": "/uploads/clean/1789051393469.jpg",
    "images": [
      "/uploads/clean/1789051393469.jpg"
    ],
    "description": "Fresh mint and sage green crochet frock set featuring hand-embroidered floral stem motifs, bow-accented bloomer shorts, and mini purse.",
    "specifications": {
      "Pieces": "Dress, Diaper Cover Shorts, Mini Bag, Booties, Headband",
      "Color": "Pastel Green / White"
    },
    "badge": "Eco Gentle",
    "isFeatured": false,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 19
  },
  {
    "id": "p-drv-bdr-red-cherry-romper",
    "name": "Handmade Crochet Baby Romper with Hanging Cherries & Floral Shoes",
    "slug": "handmade-crochet-baby-romper-hanging-cherries",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 35,
    "sku": "JM-BDR-ROMP-02",
    "image": "/uploads/clean/1789051393506.jpg",
    "images": [
      "/uploads/clean/1789051393506.jpg"
    ],
    "description": "Adorable white open-knit baby romper with red cherry tassels, ruffled cap sleeves, wooden diaper buttons, and bow-knot headband.",
    "specifications": {
      "Design": "Polka Dots & 3D Cherries",
      "Fasteners": "Wooden Bottom Snap Buttons",
      "Material": "Breathable Cotton Yarn"
    },
    "badge": "Best Seller",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 43
  },
  {
    "id": "p-drv-bdr-pink-floral-romper",
    "name": "Blush Pink Cherry Crochet Baby Onesie Romper with Floral Headband",
    "slug": "blush-pink-cherry-crochet-baby-romper",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 32,
    "sku": "JM-BDR-ROMP-03",
    "image": "/uploads/clean/1789051393541.jpg",
    "images": [
      "/uploads/clean/1789051393541.jpg"
    ],
    "description": "Tender blush pink and ivory white crochet romper with waist drawstring, dangling crocheted cherries, and flower applique booties.",
    "specifications": {
      "Details": "Adjustable Waist String with Tassels",
      "Yarn": "Anti-Allergy Baby Cotton"
    },
    "badge": "Sweet Pastel",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 27
  },
  {
    "id": "p-drv-bdr-red-floral-frock",
    "name": "Handcrafted Red Blossom Scallop Edge Baby Frock & Long Knit Booties",
    "slug": "handcrafted-red-blossom-scallop-baby-frock",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 30,
    "sku": "JM-BDR-CR-07",
    "image": "/uploads/clean/1789051393573.jpg",
    "images": [
      "/uploads/clean/1789051393573.jpg"
    ],
    "description": "Festive red and snow white crochet baby frock bordered with scalloped lace, big ribbon bow at chest, and matching high knit socks.",
    "specifications": {
      "Skirt Details": "Scalloped Floral Hem",
      "Warmth": "High Knit Baby Bootie Socks Included"
    },
    "badge": "Festive",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 39
  },
  {
    "id": "p-drv-bdr-lavender-tutu-dress",
    "name": "Princess Lavender Organza Puffed Sleeve Tutu Dress with Ribbon Headband",
    "slug": "princess-lavender-organza-tutu-baby-dress",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-baby-girls-dress",
    "subCategoryName": "Baby Girls Dress",
    "subCategorySlug": "baby-girls-dress",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 35,
    "sku": "JM-BDR-TUTU-01",
    "image": "/uploads/clean/1789051393607.jpg",
    "images": [
      "/uploads/clean/1789051393607.jpg"
    ],
    "description": "Gorgeous lilac puffed sleeves organza dress with oversized front bow and knit lace tights. Ideal for newborn milestones and naming ceremonies.",
    "specifications": {
      "Sleeves": "Puffed Fairy Cap Sleeves",
      "Accessories": "Stretch Floral Knot Headband"
    },
    "badge": "Princess",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 55
  },
  {
    "id": "p-drv-bdr-white-rosette-romper",
    "name": "Pure White Spaghetti Strap Baby Romper with 3D Rosette Flower",
    "slug": "pure-white-spaghetti-strap-baby-romper-with-rosette",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 25,
    "sku": "JM-BDR-ROMP-04",
    "image": "/uploads/clean/1789051393654.jpg",
    "images": [
      "/uploads/clean/1789051393654.jpg"
    ],
    "description": "Clean minimalist summer baby romper with large sculpted 3D center rose, adjustable shoulder straps, and soft pink crib shoes.",
    "specifications": {
      "Fabric": "Featherweight Soft Lycra Cotton",
      "Origin": "Imported"
    },
    "badge": "Summer Special",
    "isFeatured": false,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 21
  },
  {
    "id": "p-drv-bdr-corgi-winter-onesie",
    "name": "Plush Fox & Corgi Hooded Winter Flannel Baby Onesie Jumpsuit",
    "slug": "plush-corgi-hooded-winter-baby-onesie",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 40,
    "sku": "JM-BDR-WIN-01",
    "image": "/uploads/clean/1789051393684.jpg",
    "images": [
      "/uploads/clean/1789051393684.jpg"
    ],
    "description": "Thick sherpa fleece cartoon animal hooded baby jumpsuit with full zip front. Keeps your baby warm and cozy during chilly weather.",
    "specifications": {
      "Design": "Cute 3D Animal Hood with Ears",
      "Closure": "Safety Neck Guard Zip Front",
      "Material": "Warm Flannel Fleece"
    },
    "badge": "Warm & Cozy",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 62
  },
  {
    "id": "p-drv-bdr-white-eyelet-romper",
    "name": "Vintage White Eyelet Cotton Sun Romper with Tulle Flower Headband",
    "slug": "vintage-white-eyelet-cotton-sun-romper",
    "categoryId": "cat-baby-dress",
    "categoryName": "Baby Dress",
    "categorySlug": "baby-dress",
    "subCategoryId": "sub-rompers-sets",
    "subCategoryName": "Rompers & Sets",
    "subCategorySlug": "rompers-sets",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 30,
    "sku": "JM-BDR-VNT-01",
    "image": "/uploads/clean/1789051393716.jpg",
    "images": [
      "/uploads/clean/1789051393716.jpg"
    ],
    "description": "Breathable embroidered eyelet lace sleeveless baby romper with elasticated smocked chest and matching chiffon hair accessory.",
    "specifications": {
      "Fabric": "100% Breathable Broderie Anglaise Cotton"
    },
    "badge": "Vintage Pick",
    "isFeatured": false,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 20
  },
  {
    "id": "p-drv-bsh-white-heart-shoes",
    "name": "Infant Soft Sole Embroidered Heart Crib Shoes with Bow (White)",
    "slug": "infant-soft-sole-embroidered-heart-crib-shoes",
    "categoryId": "cat-baby-shoes",
    "categoryName": "Baby Shoes",
    "categorySlug": "baby-shoes",
    "subCategoryId": "sub-infant-booties",
    "subCategoryName": "Soft Sole Booties",
    "subCategorySlug": "infant-booties",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 60,
    "sku": "JM-BSH-HT-01",
    "image": "/uploads/clean/1789051394913.jpg",
    "images": [
      "/uploads/clean/1789051394913.jpg"
    ],
    "description": "Premium soft leather-feel pre-walker baby girl shoes with embroidered hearts, non-slip bottom grip, and easy velcro closure with big satin bow.",
    "specifications": {
      "Sole": "Anti-Slip Flexible Soft Sole",
      "Upper": "Supple Breathable Leatherette",
      "Closure": "Velcro Strap"
    },
    "badge": "First Walker",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 45
  },
  {
    "id": "p-drv-bsh-fishnet-bow-socks",
    "name": "Baby & Toddler Bowtie Fishnet Ruffle Knee-High Socks (Black & White)",
    "slug": "baby-toddler-bowtie-fishnet-socks",
    "categoryId": "cat-baby-shoes",
    "categoryName": "Baby Shoes",
    "categorySlug": "baby-shoes",
    "subCategoryId": "sub-toddler-sneakers",
    "subCategoryName": "Toddler Sneakers & Socks",
    "subCategorySlug": "toddler-sneakers",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 70,
    "sku": "JM-BSH-SCK-01",
    "image": "/uploads/clean/1789051394106.jpg",
    "images": [
      "/uploads/clean/1789051394106.jpg",
      "/uploads/clean/1789051394076.jpg"
    ],
    "description": "Stylish breathable hollow fishnet mesh socks for girls decorated with large satin bow ties. Looks charming paired with frocks and party dresses.",
    "specifications": {
      "Style": "Ruffle Bow Hollow Mesh",
      "Colors": "Black / White Pair",
      "Elastic": "High Stretch Non-Pinch Band"
    },
    "badge": "Trending",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 37
  },
  {
    "id": "p-drv-bsh-diamond-mesh-tights",
    "name": "Girls Diamond Butterfly Lattice Pattern Tights & Party Stockings",
    "slug": "girls-diamond-butterfly-lattice-tights",
    "categoryId": "cat-baby-shoes",
    "categoryName": "Baby Shoes",
    "categorySlug": "baby-shoes",
    "subCategoryId": "sub-toddler-sneakers",
    "subCategoryName": "Toddler Sneakers & Socks",
    "subCategorySlug": "toddler-sneakers",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 50,
    "sku": "JM-BSH-SCK-02",
    "image": "/uploads/clean/1789051394076.jpg",
    "images": [
      "/uploads/clean/1789051394076.jpg"
    ],
    "description": "Elegant diamond mesh leggings with delicate woven butterfly motifs. Perfect match with Mary Jane shoes and party frocks.",
    "specifications": {
      "Material": "Nylon & Spandex High Stretch",
      "Fit": "Toddlers & Young Girls"
    },
    "badge": "Fashion Pick",
    "isFeatured": false,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 22
  },
  {
    "id": "p-drv-ktc-degreaser-spray",
    "name": "Duer Heavy Duty Foam Kitchen Oil & Grease Cleaner Spray (500ml)",
    "slug": "duer-heavy-duty-foam-kitchen-degreaser-spray-500ml",
    "categoryId": "cat-kitchen-items",
    "categoryName": "Kitchen Items",
    "categorySlug": "kitchen-items",
    "subCategoryId": "sub-cookware-sets",
    "subCategoryName": "Cookware Sets & Cleaners",
    "subCategorySlug": "cookware-sets",
    "brand": "Duer",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 120,
    "sku": "JM-KTC-DGR-01",
    "image": "/uploads/clean/1789051394139.jpg",
    "images": [
      "/uploads/clean/1789051394139.jpg",
      "/uploads/clean/1789051394171.jpg"
    ],
    "description": "Instant powerful foaming cleaner that cuts through burnt stovetop oils, kitchen chimney grease, exhaust fans, and stainless steel cooktops with zero scrubbing.",
    "specifications": {
      "Volume": "500ml Can",
      "Formula": "Lemon Citrus Fresh Foam",
      "Application": "Gas Stoves, Range Hoods, Ovens, Tiles"
    },
    "badge": "Essential",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 88
  },
  {
    "id": "p-drv-ktc-bottle-brush-set",
    "name": "Multipurpose 360-Degree Sponge & Nipple Bottle Cleaning Brush Set",
    "slug": "multipurpose-sponge-bottle-cleaning-brush-set",
    "categoryId": "cat-kitchen-items",
    "categoryName": "Kitchen Items",
    "categorySlug": "kitchen-items",
    "subCategoryId": "sub-kitchen-accessories",
    "subCategoryName": "Kitchen Accessories & Tools",
    "subCategorySlug": "kitchen-accessories",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 90,
    "sku": "JM-KTC-BRS-01",
    "image": "/uploads/clean/1789051394885.jpg",
    "images": [
      "/uploads/clean/1789051394885.jpg"
    ],
    "description": "Complete hygienic feeding bottle and kitchen glassware cleaning kit with long ergonomic handles, dense sponge heads, and straw cleaning wires.",
    "specifications": {
      "Pieces": "Set of 4+ Brushes",
      "Head": "Dual High Density Sponge & Nylon Bristles",
      "BPA Free": "100% Food Safe"
    },
    "badge": "Best Value",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 46
  },
  {
    "id": "p-drv-wnt-rabbit-earmuffs-airbag",
    "name": "Moving Airbag Rabbit Ears Plush Winter Earmuffs with Lights",
    "slug": "moving-airbag-rabbit-ears-plush-winter-earmuffs",
    "categoryId": "cat-winter-items",
    "categoryName": "Winter Items",
    "categorySlug": "winter-items",
    "subCategoryId": "sub-winter-caps-socks",
    "subCategoryName": "Winter Caps & Socks",
    "subCategorySlug": "winter-caps-socks",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 80,
    "sku": "JM-WNT-EAR-01",
    "image": "/uploads/clean/1789051393866.jpg",
    "images": [
      "/uploads/clean/1789051393866.jpg",
      "/uploads/clean/1789051393898.jpg",
      "/uploads/clean/1789051393932.jpg",
      "/uploads/clean/1789051393964.jpg",
      "/uploads/clean/1789051393994.jpg",
      "/uploads/clean/1789051394025.jpg",
      "/uploads/clean/1789051394051.jpg"
    ],
    "description": "Super cute rabbit ear moving earmuffs! Press the soft hanging paws and the ears flap happily up and down. Keeps ears comfortably warm and protected from cold winds.",
    "specifications": {
      "Feature": "Airbag Pump Flapping Ears",
      "Material": "Super Soft Faux Fur Fluff",
      "Colors": "Pink, Yellow, Lavender, White"
    },
    "badge": "Viral Hit",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 94
  },
  {
    "id": "p-drv-wnt-plush-round-earmuffs",
    "name": "Ultra-Warm Fluffy Faux Fur Ear Warmers (Multi Colors)",
    "slug": "ultra-warm-fluffy-faux-fur-ear-warmers",
    "categoryId": "cat-winter-items",
    "categoryName": "Winter Items",
    "categorySlug": "winter-items",
    "subCategoryId": "sub-winter-caps-socks",
    "subCategoryName": "Winter Caps & Socks",
    "subCategorySlug": "winter-caps-socks",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 75,
    "sku": "JM-WNT-EAR-02",
    "image": "/uploads/clean/1789051393804.jpg",
    "images": [
      "/uploads/clean/1789051393804.jpg",
      "/uploads/clean/1789051393761.jpg",
      "/uploads/clean/1789051393836.jpg"
    ],
    "description": "Classic lightweight thermal ear muffs made of plush thick faux rabbit fur. Flexible headband suitable for teenagers, women, and kids.",
    "specifications": {
      "Fit": "Flexible Adjustable Band",
      "Lining": "High Density Plush Fur",
      "Colors": "Pink, Beige, Grey, Rose Red"
    },
    "badge": "Winter Must",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.8,
    "reviewCount": 35
  },
  {
    "id": "p-drv-gft-sakura-umbrella",
    "name": "Japanese Sakura Blossom Clear Transparent Automatic Umbrella",
    "slug": "japanese-sakura-blossom-clear-transparent-umbrella",
    "categoryId": "cat-weather-items",
    "categoryName": "Weather & Umbrella",
    "categorySlug": "weather-items",
    "subCategoryId": "sub-umbrellas",
    "subCategoryName": "Umbrellas & Parasols",
    "subCategorySlug": "umbrellas",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 65,
    "sku": "JM-GFT-UMB-01",
    "image": "/uploads/clean/1789051394753.jpg",
    "images": [
      "/uploads/clean/1789051394753.jpg",
      "/uploads/clean/1789051394617.jpg",
      "/uploads/clean/1789051394675.jpg"
    ],
    "description": "Iconic transparent dome umbrella with beautiful pink cherry blossom floral prints. Windproof fiberglass ribs and crystal clear canopy for romantic rainy days.",
    "specifications": {
      "Canopy": "Clear POE Eco Film",
      "Diameter": "96cm",
      "Windproof": "8 Sturdy Fiberglass Ribs"
    },
    "badge": "Aesthetic Gift",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 78
  },
  {
    "id": "p-drv-gft-capsule-mini-umbrella",
    "name": "7-inch Pocket Mini Folding Capsule Umbrella with Case",
    "slug": "7-inch-pocket-mini-folding-capsule-umbrella",
    "categoryId": "cat-weather-items",
    "categoryName": "Weather & Umbrella",
    "categorySlug": "weather-items",
    "subCategoryId": "sub-umbrellas",
    "subCategoryName": "Umbrellas & Parasols",
    "subCategorySlug": "umbrellas",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 70,
    "sku": "JM-GFT-UMB-02",
    "image": "/uploads/clean/1789051394709.jpg",
    "images": [
      "/uploads/clean/1789051394709.jpg"
    ],
    "description": "Ultra-compact lightweight pocket umbrella packed into a waterproof capsule case. Blocks 99% UV rays with vinyl sunscreen coating.",
    "specifications": {
      "Folded Size": "18cm (7 inches)",
      "Weight": "210g Ultralight",
      "UV Protection": "UPF 50+"
    },
    "badge": "Pocket Essential",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 52
  },
  {
    "id": "p-drv-gft-hellokitty-clear-umbrella",
    "name": "Hello Kitty Kids Transparent Dome Umbrella with Ice Cream Print",
    "slug": "hello-kitty-kids-transparent-dome-umbrella",
    "categoryId": "cat-weather-items",
    "categoryName": "Weather & Umbrella",
    "categorySlug": "weather-items",
    "subCategoryId": "sub-umbrellas",
    "subCategoryName": "Umbrellas & Parasols",
    "subCategorySlug": "umbrellas",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 55,
    "sku": "JM-GFT-UMB-03",
    "image": "/uploads/clean/1789051394787.jpg",
    "images": [
      "/uploads/clean/1789051394787.jpg"
    ],
    "description": "Transparent safety view deep-dome umbrella featuring licensed Hello Kitty graphics. Rounded safety tips protect children during school walks.",
    "specifications": {
      "Safety": "Pinch-proof Runner & Round Tips",
      "Canopy": "Clear View POE Plastic"
    },
    "badge": "Kids Love",
    "isFeatured": true,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.9,
    "reviewCount": 36
  },
  {
    "id": "p-drv-gft-fruit-folding-umbrella",
    "name": "Colorful Summer Fruit Print Windproof Folding Umbrellas",
    "slug": "colorful-summer-fruit-print-folding-umbrella",
    "categoryId": "cat-weather-items",
    "categoryName": "Weather & Umbrella",
    "categorySlug": "weather-items",
    "subCategoryId": "sub-umbrellas",
    "subCategoryName": "Umbrellas & Parasols",
    "subCategorySlug": "umbrellas",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 45,
    "sku": "JM-GFT-UMB-04",
    "image": "/uploads/clean/1789051394645.jpg",
    "images": [
      "/uploads/clean/1789051394645.jpg"
    ],
    "description": "Refreshing fruit prints (Peach, Watermelon, Lemon, Kiwi) 3-fold rain and sun umbrella with vinyl black thermal coating for UV protection.",
    "specifications": {
      "Themes": "Peach, Lemon, Orange, Watermelon",
      "Ribs": "8 Black Steel Windproof Ribs"
    },
    "badge": "Summer Fresh",
    "isFeatured": false,
    "isBestSeller": false,
    "isNew": true,
    "isActive": true,
    "rating": 4.7,
    "reviewCount": 18
  },
  {
    "id": "p-drv-gft-mermaid-kids-raincoat",
    "name": "Kids Waterproof Hooded Raincoat with School Bag Back Gusset (Pink Mermaid)",
    "slug": "kids-waterproof-hooded-raincoat-mermaid",
    "categoryId": "cat-weather-items",
    "categoryName": "Weather & Umbrella",
    "categorySlug": "weather-items",
    "subCategoryId": "sub-kids-rainwear",
    "subCategoryName": "Kids Rainwear & Raincoats",
    "subCategorySlug": "raincoats",
    "brand": "Jawata Mart",
    "price": 0,
    "originalPrice": 0,
    "discount": 0,
    "stock": 50,
    "sku": "JM-GFT-RNC-01",
    "image": "/uploads/clean/1789051394942.jpg",
    "images": [
      "/uploads/clean/1789051394942.jpg"
    ],
    "description": "Premium EVA waterproof breathable kids raincoat with expandable backpack pocket on the back and extended transparent hood brim.",
    "specifications": {
      "Design": "Expandable School Bag Space",
      "Material": "Eco Friendly Odorless EVA",
      "Visor": "Clear Rain Visor Hood"
    },
    "badge": "Monsoon Ready",
    "isFeatured": true,
    "isBestSeller": true,
    "isNew": true,
    "isActive": true,
    "rating": 5,
    "reviewCount": 41
  },
  // 1. Bag
  {
    id: 'p-bag-school-ortho',
    name: 'Ergonomic Waterproof Orthopedic School Backpack (32L)',
    slug: 'ergonomic-waterproof-school-backpack',
    categoryId: 'cat-bag',
    categoryName: 'Bag',
    categorySlug: 'bag',
    subCategoryId: 'sub-school-bag',
    subCategoryName: 'School Bag',
    subCategorySlug: 'school-bag',
    brand: 'Jawata Mart',
    price: 1650,
    originalPrice: 2200,
    discount: 25,
    stock: 50,
    sku: 'JM-BAG-SCH-01',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop'],
    description: 'Heavy duty waterproof Oxford cloth school bag with spine protection cushioning and multiple stationery compartments.',
    specifications: { 'Capacity': '32 Liters', 'Material': 'Waterproof Oxford Polyester', 'Weight': '650g' },
    badge: 'Bestseller',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 154,
  },
  {
    id: 'p-bag-kids-dino',
    name: 'Cute 3D Dinosaur Plush Kids Toddler Backpack',
    slug: 'cute-3d-dinosaur-kids-backpack',
    categoryId: 'cat-bag',
    categoryName: 'Bag',
    categorySlug: 'bag',
    subCategoryId: 'sub-kids-bag',
    subCategoryName: 'Kids Bag',
    subCategorySlug: 'kids-bag',
    brand: 'Jawata Mart',
    price: 850,
    originalPrice: 1150,
    discount: 26,
    stock: 65,
    sku: 'JM-BAG-KID-02',
    image: 'https://images.unsplash.com/photo-1577733966973-d680bffd2e80?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1577733966973-d680bffd2e80?w=600&h=600&fit=crop'],
    description: 'Soft neoprene lightweight anti-lost backpack for preschool and nursery kids with adjustable safety harness.',
    specifications: { 'Age Range': '1-5 Years', 'Material': 'Eco Neoprene', 'Feature': 'Anti-Lost Harness' },
    badge: 'Popular',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: 'p-bag-ladies-tote',
    name: 'Premium Vegan Leather Ladies Shoulder Handbag & Crossbody Set',
    slug: 'premium-leather-ladies-handbag-set',
    categoryId: 'cat-bag',
    categoryName: 'Bag',
    categorySlug: 'bag',
    subCategoryId: 'sub-ladies-bag',
    subCategoryName: 'Ladies Bag',
    subCategorySlug: 'ladies-bag',
    brand: 'Jawata Mart',
    price: 2150,
    originalPrice: 2800,
    discount: 23,
    stock: 35,
    sku: 'JM-BAG-LAD-03',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=600&fit=crop'],
    description: 'Elegant dual-tone ladies tote handbag equipped with gold-plated metal zippers, inner organizer pouch, and detachable strap.',
    specifications: { 'Material': 'High Grade Vegan Leather', 'Compartments': '3 Inner, 1 Zipper', 'Closure': 'Magnetic & Zip' },
    badge: 'New Arrival',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 210,
  },
  {
    id: 'p-bag-travel-duffel',
    name: 'Expandable Cabin Waterproof Travelling Duffel Bag (55L)',
    slug: 'expandable-waterproof-travelling-duffel-bag',
    categoryId: 'cat-bag',
    categoryName: 'Bag',
    categorySlug: 'bag',
    subCategoryId: 'sub-travelling-bag',
    subCategoryName: 'Travelling Bag',
    subCategorySlug: 'travelling-bag',
    brand: 'Jawata Mart',
    price: 1750,
    originalPrice: 2400,
    discount: 27,
    stock: 40,
    sku: 'JM-BAG-TRV-04',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop'],
    description: 'Foldable large capacity duffle bag with wet/dry separation pocket and luggage sleeve.',
    specifications: { 'Capacity': '55 Liters', 'Feature': 'Foldable & Luggage Compatible', 'Usage': 'Weekend & Flight Travel' },
    badge: 'Trending',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 88,
  },

  // 2. Kids Toys
  {
    id: 'p-toy-rc-stunt-car',
    name: '4WD 360° Rotating High-Speed Gesture & Remote Control Stunt Car',
    slug: '4wd-gesture-rc-stunt-car',
    categoryId: 'cat-kids-toys',
    categoryName: 'Kids Toys',
    categorySlug: 'kids-toys',
    subCategoryId: 'sub-rc-cars',
    subCategoryName: 'Remote Control & Cars',
    subCategorySlug: 'rc-cars',
    brand: 'Jawata Mart',
    price: 1950,
    originalPrice: 2600,
    discount: 25,
    stock: 45,
    sku: 'JM-TOY-RC-01',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&h=600&fit=crop'],
    description: 'Exciting gesture sensor control car with LED headlights, realistic engine audio, and all-terrain stunt tumbling wheels.',
    specifications: { 'Control Mode': 'Hand Gesture + 2.4GHz Remote', 'Battery': 'Rechargeable Li-ion', 'Play Time': '40 Mins' },
    badge: 'Top Rated',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 165,
  },
  {
    id: 'p-toy-wooden-montessori',
    name: '10-in-1 Wooden Educational Geometry & Number Sorting Puzzle',
    slug: '10-in-1-wooden-montessori-puzzle',
    categoryId: 'cat-kids-toys',
    categoryName: 'Kids Toys',
    categorySlug: 'kids-toys',
    subCategoryId: 'sub-educational-toys',
    subCategoryName: 'Educational Toys',
    subCategorySlug: 'educational-toys',
    brand: 'Jawata Mart',
    price: 1250,
    originalPrice: 1650,
    discount: 24,
    stock: 60,
    sku: 'JM-TOY-EDU-02',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&h=600&fit=crop'],
    description: 'Eco-friendly non-toxic natural wood matching puzzle for motor skills, color identification, and basic math counting.',
    specifications: { 'Material': 'Natural Beech Wood & Non-Toxic Paint', 'Age': '2-6 Years', 'Certifications': 'CE Certified' },
    badge: 'Bestseller',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 220,
  },

  // 3. Baby Dress
  {
    id: 'p-dress-organic-romper-3pk',
    name: '100% Organic Pure Cotton Baby Rompers & Bodysuits (Pack of 3)',
    slug: 'organic-cotton-baby-rompers-3pk',
    categoryId: 'cat-baby-dress',
    categoryName: 'Baby Dress',
    categorySlug: 'baby-dress',
    subCategoryId: 'sub-rompers-sets',
    subCategoryName: 'Rompers & Sets',
    subCategorySlug: 'rompers-sets',
    brand: 'Jawata Mart',
    price: 1350,
    originalPrice: 1800,
    discount: 25,
    stock: 80,
    sku: 'JM-DRS-RMP-01',
    image: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600&h=600&fit=crop'],
    description: 'Hypoallergenic soft breathable cotton onesies with nickel-free crotch snap buttons for hassle-free diaper changing.',
    specifications: { 'Fabric': '100% Combed Cotton', 'Sizes': '0-3M, 3-6M, 6-12M', 'Wash': 'Machine Washable' },
    badge: 'Hot Deal',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 310,
  },
  {
    id: 'p-dress-newborn-set',
    name: 'Newborn Welcome Hospital Gift Set (8 Pcs Complete Cotton Clothing)',
    slug: 'newborn-welcome-gift-set-8pcs',
    categoryId: 'cat-baby-dress',
    categoryName: 'Baby Dress',
    categorySlug: 'baby-dress',
    subCategoryId: 'sub-newborn-clothes',
    subCategoryName: 'Newborn Clothes',
    subCategorySlug: 'newborn-clothes',
    brand: 'Jawata Mart',
    price: 1650,
    originalPrice: 2150,
    discount: 23,
    stock: 55,
    sku: 'JM-DRS-NWB-02',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&h=600&fit=crop'],
    description: 'Includes 2 tops, 2 pajamas, cap, mittens, booties, and bib in an elegant gift box presentation.',
    specifications: { 'Items': '8 Pieces Set', 'Material': 'Interlock Baby Cotton', 'Target Age': '0-3 Months' },
    badge: 'Gift Choice',
    isFeatured: false,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 140,
  },

  // 4. Baby Shoes
  {
    id: 'p-shoe-soft-booties',
    name: 'Anti-Slip Breathable Soft Sole Pre-Walker Infant Booties',
    slug: 'anti-slip-soft-sole-infant-booties',
    categoryId: 'cat-baby-shoes',
    categoryName: 'Baby Shoes',
    categorySlug: 'baby-shoes',
    subCategoryId: 'sub-soft-sole-booties',
    subCategoryName: 'Soft Sole Booties',
    subCategorySlug: 'soft-sole-booties',
    brand: 'Jawata Mart',
    price: 650,
    originalPrice: 850,
    discount: 23,
    stock: 70,
    sku: 'JM-SHU-BOT-01',
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=600&h=600&fit=crop'],
    description: 'Elastic ankle cuff holds booties securely without restricting natural baby foot development. Non-slip silicone bottom.',
    specifications: { 'Sole': 'Anti-skid Soft Rubber Grip', 'Sizes': '11cm, 12cm, 13cm', 'Seasons': 'All Seasons' },
    badge: 'Popular',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.7,
    reviewCount: 115,
  },

  // 5. Cosmetics Items
  {
    id: 'p-cosm-aveeno-wash',
    name: 'Aveeno Baby Daily Moisture Tear-Free Wash & Shampoo 354ml',
    slug: 'aveeno-baby-daily-moisture-wash-shampoo',
    categoryId: 'cat-cosmetics-items',
    categoryName: 'Cosmetics Items (Baby & Parents)',
    categorySlug: 'cosmetics-items',
    subCategoryId: 'sub-baby-skincare-wash',
    subCategoryName: 'Baby Skincare & Wash',
    subCategorySlug: 'baby-skincare-wash',
    brand: 'Aveeno',
    price: 1350,
    originalPrice: 1650,
    discount: 18,
    stock: 65,
    sku: 'JM-CSM-AVN-01',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop'],
    description: 'Tear-free hypoallergenic wash formulated with natural oat extract to gently nourish delicate infant skin.',
    specifications: { 'Volume': '354 ml', 'Origin': 'USA / EU', 'Hypoallergenic': 'Yes, Dermatologist Tested' },
    badge: 'Authentic',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 320,
  },

  // 6. Gift Item
  {
    id: 'p-gift-islamic-box',
    name: 'Luxury Velvet Islamic Gift Box (Quran, Prayer Mat & Crystal Tasbeeh)',
    slug: 'luxury-velvet-islamic-gift-box',
    categoryId: 'cat-gift-item',
    categoryName: 'Gift Item',
    categorySlug: 'gift-item',
    subCategoryId: 'sub-islamic-gift-sets',
    subCategoryName: 'Islamic Gift Sets',
    subCategorySlug: 'islamic-gift-sets',
    brand: 'Jawata Mart',
    price: 2450,
    originalPrice: 3200,
    discount: 23,
    stock: 30,
    sku: 'JM-GFT-ISL-01',
    image: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600&h=600&fit=crop'],
    description: 'Gold-embossed Quran Sharif, Turkish plush velvet Janamaz, fragrant Oud Attar, and 99-bead crystal Tasbeeh.',
    specifications: { 'Box Material': 'Velvet Gift Trunk', 'Contents': 'Quran + Janamaz + Attar + Tasbeeh', 'Occasion': 'Eid, Hajj, Nikah' },
    badge: 'Premium Gift',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 5.0,
    reviewCount: 86,
  },

  // 7. Home Tex
  {
    id: 'p-htex-curtain-luxury',
    name: 'Modern Eyelet Thermal Blackout Room Curtains (Set of 2 Panels)',
    slug: 'modern-eyelet-thermal-blackout-curtains',
    categoryId: 'cat-home-tex',
    categoryName: 'Home Tex',
    categorySlug: 'home-tex',
    subCategoryId: 'sub-curtains-drapes',
    subCategoryName: 'Curtains & Drapes',
    subCategorySlug: 'curtains-drapes',
    brand: 'Jawata Mart',
    price: 1850,
    originalPrice: 2500,
    discount: 26,
    stock: 40,
    sku: 'JM-HTX-CRT-01',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&h=600&fit=crop'],
    description: 'Blocks 90% sunlight and UV rays, reduces outside noise, and provides temperature insulation.',
    specifications: { 'Dimensions': '7 Ft x 4 Ft each (Pack of 2)', 'Fabric': 'Heavy Triple-Weave Polyester', 'Hanging': 'Rust-Proof Eyelets' },
    badge: 'Top Rated',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 94,
  },

  // 8. Bed Sheet
  {
    id: 'p-bed-king-cotton',
    name: '100% Pure Combed Cotton King Size Printed Bedsheet Set (with 2 Pillowcases)',
    slug: 'pure-combed-cotton-king-size-bedsheet',
    categoryId: 'cat-bed-sheet',
    categoryName: 'Bed Sheet',
    categorySlug: 'bed-sheet',
    subCategoryId: 'sub-double-king-bed-sheets',
    subCategoryName: 'Double & King Bed Sheets',
    subCategorySlug: 'double-king-bed-sheets',
    brand: 'Jawata Mart',
    price: 1650,
    originalPrice: 2200,
    discount: 25,
    stock: 50,
    sku: 'JM-BED-KNG-01',
    image: 'https://images.unsplash.com/photo-1629949009765-40fc74c95018?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1629949009765-40fc74c95018?w=600&h=600&fit=crop'],
    description: 'Ultra-soft 300 Thread Count breathable cotton with anti-fade reactive floral printing. Does not shrink or pill.',
    specifications: { 'Size': 'King (7.5 Ft x 8.5 Ft)', 'Thread Count': '300 TC', 'Includes': '1 Bedsheet + 2 Matching Pillow Covers' },
    badge: 'Bestseller',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.9,
    reviewCount: 188,
  },

  // 9. Educational Items
  {
    id: 'p-edu-quran-series',
    name: 'Illustrated Islamic History & Stories of 25 Prophets for Children (4 Volumes)',
    slug: 'stories-of-prophets-children-series',
    categoryId: 'cat-educational-items',
    categoryName: 'Educational Items',
    categorySlug: 'educational-items',
    subCategoryId: 'sub-islamic-general-books',
    subCategoryName: 'Islamic & General Books',
    subCategorySlug: 'islamic-general-books',
    brand: 'Jawata Mart',
    price: 1150,
    originalPrice: 1550,
    discount: 25,
    stock: 55,
    sku: 'JM-EDU-BOK-01',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=600&fit=crop'],
    description: 'Full-color illustrated hardbound book series written in engaging Bangla and English for young curious minds.',
    specifications: { 'Binding': 'Hardcover 4 Volumes', 'Language': 'Bangla with Arabic Reference', 'Target Age': '5-14 Years' },
    badge: 'Recommended',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 5.0,
    reviewCount: 145,
  },

  // 10. Kitchen Items
  {
    id: 'p-kitch-granite-set',
    name: 'Die-Cast Non-Stick Granite Cookware Set (7 Pcs with Tempered Glass Lids)',
    slug: 'die-cast-granite-cookware-set-7pcs',
    categoryId: 'cat-kitchen-items',
    categoryName: 'Kitchen Items',
    categorySlug: 'kitchen-items',
    subCategoryId: 'sub-cookware-pots',
    subCategoryName: 'Cookware & Pots',
    subCategorySlug: 'cookware-pots',
    brand: 'Jawata Mart',
    price: 4650,
    originalPrice: 5900,
    discount: 21,
    stock: 25,
    sku: 'JM-KIT-CW-01',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&h=600&fit=crop'],
    description: 'Multi-layer durable German granite coating. Induction and gas stove compatible with heat-resistant silicone handles.',
    specifications: { 'Set Count': '7 Pieces (Casseroles, Pan, Kadai, Lids)', 'Coating': 'PFOA-Free Granite Non-Stick', 'Base': 'Induction Bottom' },
    badge: 'Chef Choice',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 75,
  },

  // 11. Health Care & Skin Care
  {
    id: 'p-hlth-vitc-serum',
    name: 'Pure Organic Vitamin C Brightening & Anti-Aging Serum 30ml',
    slug: 'pure-organic-vitamin-c-serum',
    categoryId: 'cat-health-skin-care',
    categoryName: 'Health Care & Skin Care Items',
    categorySlug: 'health-skin-care',
    subCategoryId: 'sub-organic-face-care',
    subCategoryName: 'Organic Face Care',
    subCategorySlug: 'organic-face-care',
    brand: 'Jawata Mart',
    price: 950,
    originalPrice: 1350,
    discount: 29,
    stock: 75,
    sku: 'JM-SKN-SER-01',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop'],
    description: 'Infused with 20% Vitamin C, Hyaluronic acid and Vitamin E. Fades dark spots and boosts natural collagen.',
    specifications: { 'Volume': '30 ml Dropper Bottle', 'Key Actives': '20% L-Ascorbic Acid, Hyaluronic Acid', 'Skin Type': 'All Skin Types' },
    badge: 'Popular',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 4.8,
    reviewCount: 230,
  },

  // 12. Islamic Items
  {
    id: 'p-isl-prayer-mat-velvet',
    name: 'Turkish Embossed Memory Foam Luxury Velvet Janamaz (Prayer Mat)',
    slug: 'turkish-embossed-memory-foam-janamaz',
    categoryId: 'cat-islamic-items',
    categoryName: 'Islamic Items',
    categorySlug: 'islamic-items',
    subCategoryId: 'sub-janamaz-prayer-mats',
    subCategoryName: 'Premium Janamaz (Prayer Mats)',
    subCategorySlug: 'janamaz-prayer-mats',
    brand: 'Jawata Mart',
    price: 1850,
    originalPrice: 2400,
    discount: 23,
    stock: 45,
    sku: 'JM-ISL-JNM-01',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&h=600&fit=crop'],
    description: 'Extra thick orthopedic memory foam cushioning eases knee and joint pressure during Sajdah. Anti-slip bottom.',
    specifications: { 'Cushioning': '20mm High Density Memory Foam', 'Surface': 'Plush Turkish Velvet', 'Dimensions': '120cm x 80cm' },
    badge: 'Comfort Pick',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    rating: 5.0,
    reviewCount: 312,
  },

  // 13. Winter Items
  {
    id: 'p-wnt-fleece-hoodie',
    name: 'Thermal Fleece Lined Baby Winter Zipper Hoodie Jacket',
    slug: 'thermal-fleece-baby-winter-hoodie',
    categoryId: 'cat-winter-items',
    categoryName: 'Winter Items',
    categorySlug: 'winter-items',
    subCategoryId: 'sub-baby-winter-sweaters',
    subCategoryName: 'Baby Winter Sweaters & Hoodies',
    subCategorySlug: 'baby-winter-sweaters',
    brand: 'Jawata Mart',
    price: 1150,
    originalPrice: 1550,
    discount: 25,
    stock: 65,
    sku: 'JM-WNT-HOD-01',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop'],
    description: 'Ultra-warm windproof sherpa fleece interior with cute animal ear hood design. Protects babies from cold breeze.',
    specifications: { 'Lining': 'Warm Sherpa Fleece', 'Closure': 'Smooth Zip Front', 'Sizes': '6M-12M, 1-2Y, 2-3Y' },
    badge: 'Winter Special',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    rating: 4.9,
    reviewCount: 160,
  }
];

export const INITIAL_BANNERS: BannerItem[] = [
  {
    id: 'ban-cover',
    title: '',
    subtitle: '',
    image: '/jawata-mart-cover.jpg',
    ctaText: 'Shop Now',
    ctaLink: '/category/all',
    order: 1,
    isActive: true,
  },
  {
    id: 'ban-1',
    title: 'Jawata Mart - Pure & Authentic Lifestyle Shopping',
    subtitle: '10,000+ Genuine Family & Kids Essentials with Fast Nationwide Delivery from Uttara, Dhaka.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1600&h=600&fit=crop',
    ctaText: 'Shop Now',
    ctaLink: '/category/all',
    order: 2,
    isActive: true,
  },
  {
    id: 'ban-2',
    title: 'Premium Bags, Toys & Kids Fashion Collection',
    subtitle: 'From school backpacks and Montessori toys to soft baby shoes and dresses.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1600&h=600&fit=crop',
    ctaText: 'Explore Collection',
    ctaLink: '/category/bag',
    order: 3,
    isActive: true,
  },
  {
    id: 'ban-3',
    title: 'Home Tex, Bedsheets & Islamic Lifestyle',
    subtitle: '100% pure cotton king bedsheets, blackout curtains, luxury velvet Janamaz and Quran sets.',
    image: 'https://images.unsplash.com/photo-1629949009765-40fc74c95018?w=1600&h=600&fit=crop',
    ctaText: 'View Home Tex',
    ctaLink: '/category/home-tex',
    order: 4,
    isActive: true,
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 'c-welcome10',
    code: 'WELCOME10',
    type: 'PERCENTAGE',
    value: 10,
    minOrder: 1000,
    maxDiscount: 200,
    usedCount: 0,
    isActive: true,
    expiryDate: '2026-12-31',
  },
  {
    id: 'c-ramadan2026',
    code: 'RAMADAN2026',
    type: 'FIXED',
    value: 150,
    minOrder: 1500,
    usedCount: 0,
    isActive: true,
    expiryDate: '2026-12-31',
  },
];

export const INITIAL_REVIEWS = [
  {
    id: 'r1',
    name: 'Tasnim Akter',
    location: 'Dhanmondi, Dhaka',
    rating: 5,
    date: '02 Mar 2026',
    comment: 'Super fast delivery to Dhaka! Got the Pampers diapers and Aveeno wash within 24 hours. Well packaged and 100% original.',
    verified: true,
    avatar: 'TA',
  },
  {
    id: 'r2',
    name: 'Roksana Begum',
    location: 'Chittagong City',
    rating: 5,
    date: '28 Feb 2026',
    comment: 'Ordered the Aarong Saree for my family. The zari work is gorgeous, exactly as displayed on the website. Very happy with the cash on delivery service.',
    verified: true,
    avatar: 'RB',
  },
  {
    id: 'r3',
    name: 'Mahmud Hossain',
    location: 'Sylhet Sadar',
    rating: 5,
    date: '25 Feb 2026',
    comment: 'Bought the U-shaped pregnancy pillow for my wife. It relieved her back pain immediately. Customer support via hotline was exceptionally polite!',
    verified: true,
    avatar: 'MH',
  },
  {
    id: 'r4',
    name: 'Karim Uddin',
    location: 'Uttara, Dhaka',
    rating: 5,
    date: '20 Feb 2026',
    comment: 'Paid with bKash Send Money. The verification was confirmed within 15 minutes and the Panjabi arrived the next morning. Highly recommended!',
    verified: true,
    avatar: 'KU',
  },
];

